Pscf::Pspg::Continuous::Polymer< D > Class Template Reference
Descriptor and solver for a branched polymer species.
#include <Polymer.h>
Public Member Functions
void compute (DArray< WField > const &wFields)
Compute solution to MDE and concentrations.
void computeVertex (const Mesh< D > &mesh)
Compute vertex density fields.
void computeStress (WaveList< D > &wavelist)
Compute stress from a polymer chain, needs a pointer to basis.
double stress (int n)
Get derivative of free energy w/ respect to a unit cell parameter.
Protected Member Functions
void setClassName (const char *className)
Set class name string.
Additional Inherited Members
Detailed Description
template<int D>
class Pscf::Pspg::Continuous::Polymer< D >
Descriptor and solver for a branched polymer species.
The block concentrations stored in the constituent Block<D> objects contain the block concentrations (i.e., volume fractions) computed in the most recent call of the compute function.
The phi() and mu() accessor functions, which are inherited from PolymerTmp< Block<D> >, return the value of phi (spatial average volume fraction of a species) or mu (chemical potential) computed in the last call of the compute function. If the ensemble for this species is closed, phi is read from the parameter file and mu is computed. If the ensemble is open, mu is read from the parameter file and phi is computed.
Definition at line 44 of file Polymer.h.
Member Function Documentation
compute()
template<int D>
void Pscf::Pspg::Continuous::Polymer< D >::compute (DArray< WField > const & wFields)
Compute solution to MDE and concentrations.
Definition at line 66 of file Polymer.tpp.
computeVertex()
template<int D>
void Pscf::Pspg::Continuous::Polymer< D >::computeVertex (const Mesh< D > & mesh)
Compute vertex density fields.
Definition at line 135 of file Polymer.tpp.
References Pscf::Mesh< D >::dimensions(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), and Pscf::Mesh< D >::size().
computeStress()
template<int D>
void Pscf::Pspg::Continuous::Polymer< D >::computeStress (WaveList< D > & wavelist)
Compute stress from a polymer chain, needs a pointer to basis.
Definition at line 186 of file Polymer.tpp.
stress()
template<int D>
cudaReal Pscf::Pspg::Continuous::Polymer< D >::stress (int n) [inline]
Get derivative of free energy w/ respect to a unit cell parameter.
Get the contribution from this polymer species to the derivative of free energy per monomer with respect to unit cell parameter n.
Parameters
n unit cell parameter index
Definition at line 126 of file Polymer.h.
setClassName()
template<int D>
void Util::ParamComposite::setClassName [protected]
Set class name string.
Should be set in subclass constructor.
Definition at line 377 of file ParamComposite.cpp.
The documentation for this class was generated from the following files:
Polymer.h
Polymer.tpp