Pscf::Pspg::FieldIo< D > Class Template Reference
File input/output operations for fields in several file formats.
#include <FieldIo.h>
Public Member Functions
FieldIo ()
Constructor.
~FieldIo ()
Destructor.
void associate (UnitCell< D > &unitCell, Mesh< D > &mesh, FFT< D > &fft, std::string &groupName, Basis< D > &basis, FileMaster &fileMaster)
Get and store addresses of associated objects.
 Field File IO
void readFieldsBasis (std::istream &in, DArray< RDField< D > > &fields)
Read concentration or chemical potential field components from file.
void readFieldsBasis (std::string filename, DArray< RDField< D > > &fields)
Read concentration or chemical potential field components from file.
void writeFieldsBasis (std::ostream &out, DArray< RDField< D > > const &fields)
Write concentration or chemical potential field components to file.
void writeFieldsBasis (std::string filename, DArray< RDField< D > > const &fields)
Write concentration or chemical potential field components to file.
void readFieldsRGrid (std::istream &in, DArray< RDField< D > > &fields)
Read array of RField objects (fields on an r-space grid) from file.
void readFieldsRGrid (std::string filename, DArray< RDField< D > > &fields)
Read array of RField objects (fields on an r-space grid) from file.
void writeFieldsRGrid (std::ostream &out, DArray< RDField< D > > const &fields)
Write array of RField objects (fields on an r-space grid) to file.
void writeFieldsRGrid (std::string filename, DArray< RDField< D > > const &fields)
Write array of RField objects (fields on an r-space grid) to file.
void readFieldsKGrid (std::istream &in, DArray< RDFieldDft< D > > &fields)
Read array of RFieldDft objects (k-space fields) from file.
void readFieldsKGrid (std::string filename, DArray< RDFieldDft< D > > &fields)
Read array of RFieldDft objects (k-space fields) from file.
void writeFieldsKGrid (std::ostream &out, DArray< RDFieldDft< D > > const &fields)
Write array of RFieldDft objects (k-space fields) to file.
void writeFieldsKGrid (std::string filename, DArray< RDFieldDft< D > > const &fields)
Write array of RFieldDft objects (k-space fields) to a file.
void writeFieldHeader (std::ostream &out, int nMonomer) const
Write header for field file (fortran pscf format)
Field Format Conversion
void convertBasisToKGrid (RDField< D > const &components, RDFieldDft< D > &dft)
Convert field from symmetrized basis to Fourier transform (k-grid).
void convertBasisToKGrid (DArray< RDField< D > > &in, DArray< RDFieldDft< D > > &out)
Convert fields from symmetrized basis to Fourier transform (kgrid).
void convertKGridToBasis (RDFieldDft< D > const &dft, RDField< D > &components)
Convert field from Fourier transform (k-grid) to symmetrized basis.
void convertKGridToBasis (DArray< RDFieldDft< D > > &in, DArray< RDField< D > > &out)
Convert fields from Fourier transform (kgrid) to symmetrized basis.
void convertBasisToRGrid (DArray< RDField< D > > &in, DArray< RDField< D > > &out)
Convert fields from symmetrized basis to spatial grid (rgrid).
void convertRGridToBasis (DArray< RDField< D > > &in, DArray< RDField< D > > &out)
Convert fields from spatial grid (rgrid) to symmetrized basis.
Detailed Description
template<int D>
class Pscf::Pspg::FieldIo< D >
File input/output operations for fields in several file formats.
Definition at line 35 of file FieldIo.h.
Constructor & Destructor Documentation
FieldIo()
template<int D>
Pscf::Pspg::FieldIo< D >::FieldIo
Constructor.
Definition at line 34 of file FieldIo.tpp.
 FieldIo()
template<int D>
Pscf::Pspg::FieldIo< D >::~FieldIo
Destructor.
Definition at line 47 of file FieldIo.tpp.
Member Function Documentation
associate()
template<int D>
void Pscf::Pspg::FieldIo< D >::associate (UnitCell< D > & unitCell, Mesh< D > & mesh, FFT< D > & fft, std::string & groupName, Basis< D > & basis, FileMaster & fileMaster)
Get and store addresses of associated objects.
Parameters
unitCell associated crystallographic UnitCell<D>
mesh associated spatial discretization Mesh<D>
fft associated FFT object for fast transforms
groupName space group name string
basis associated Basis object
fileMaster associated FileMaster (for file paths)
Definition at line 54 of file FieldIo.tpp.
readFieldsBasis() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::readFieldsBasis (std::istream & in, DArray< RDField< D > > & fields)
Read concentration or chemical potential field components from file.
This function reads components in a symmetry adapted basis from file in.
The capacity of DArray fields is equal to nMonomer, and element fields[i] is a DArray containing components of the field associated with monomer type i.
Parameters
in input stream (i.e., input file)
fields array of fields (symmetry adapted basis components)
Definition at line 70 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
readFieldsBasis() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::readFieldsBasis (std::string filename, DArray< RDField< D > > & fields)
Read concentration or chemical potential field components from file.
This function opens an input file with the specified filename, reads components in symmetry-adapted form from that file, and closes the file.
Parameters
filename name of input file
fields array of fields (symmetry adapted basis components)
Definition at line 147 of file FieldIo.tpp.
writeFieldsBasis() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldsBasis (std::ostream & out, DArray< RDField< D > > const & fields)
Write concentration or chemical potential field components to file.
This function writes components in a symmetry adapted basis.
Parameters
out output stream (i.e., output file)
fields array of fields (symmetry adapted basis components)
Definition at line 158 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
writeFieldsBasis() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldsBasis (std::string filename, DArray< RDField< D > > const & fields)
Write concentration or chemical potential field components to file.
This function opens an output file with the specified filename, writes components in symmetry-adapted form to that file, and then closes the file.
Parameters
filename name of input file
fields array of fields (symmetry adapted basis components)
Definition at line 206 of file FieldIo.tpp.
readFieldsRGrid() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::readFieldsRGrid (std::istream & in, DArray< RDField< D > > & fields)
Read array of RField objects (fields on an r-space grid) from file.
The capacity of array fields is equal to nMonomer, and element fields[i] is the RField<D> associated with monomer type i.
Parameters
in input stream (i.e., input file)
fields array of RField fields (r-space grid)
Definition at line 216 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
readFieldsRGrid() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::readFieldsRGrid (std::string filename, DArray< RDField< D > > & fields)
Read array of RField objects (fields on an r-space grid) from file.
The capacity of array fields is equal to nMonomer, and element fields[i] is the RField<D> associated with monomer type i.
This function opens an input file with the specified filename, reads fields in RField<D> real-space grid format from that file, and then closes the file.
Parameters
filename name of input file
fields array of RField fields (r-space grid)
Definition at line 281 of file FieldIo.tpp.
writeFieldsRGrid() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldsRGrid (std::ostream & out, DArray< RDField< D > > const & fields)
Write array of RField objects (fields on an r-space grid) to file.
Parameters
out output stream (i.e., output file)
fields array of RField fields (r-space grid)
Definition at line 291 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
writeFieldsRGrid() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldsRGrid (std::string filename, DArray< RDField< D > > const & fields)
Write array of RField objects (fields on an r-space grid) to file.
This function opens an output file with the specified filename, writes fields in RField<D> real-space grid format to that file, and then closes the file.
Parameters
filename name of output file
fields array of RField fields (r-space grid)
Definition at line 351 of file FieldIo.tpp.
readFieldsKGrid() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::readFieldsKGrid (std::istream & in, DArray< RDFieldDft< D > > & fields)
Read array of RFieldDft objects (k-space fields) from file.
The capacity of the array is equal to nMonomer, and element fields[i] is the discrete Fourier transform of the field for monomer type i.
Parameters
in input stream (i.e., input file)
fields array of RFieldDft fields (k-space grid)
Definition at line 361 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
readFieldsKGrid() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::readFieldsKGrid (std::string filename, DArray< RDFieldDft< D > > & fields)
Read array of RFieldDft objects (k-space fields) from file.
This function opens a file with name filename, reads discrete Fourier components (Dft) of fields from that file, and closes the file.
The capacity of the array is equal to nMonomer, and element fields[i] is the discrete Fourier transform of the field for monomer type i.
Parameters
filename name of input file
fields array of RFieldDft fields (k-space grid)
Definition at line 413 of file FieldIo.tpp.
writeFieldsKGrid() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldsKGrid (std::ostream & out, DArray< RDFieldDft< D > > const & fields)
Write array of RFieldDft objects (k-space fields) to file.
The capacity of the array fields is equal to nMonomer. Element fields[i] is the discrete Fourier transform of the field for monomer type i.
Parameters
out output stream (i.e., output file)
fields array of RFieldDft fields
Definition at line 423 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
writeFieldsKGrid() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldsKGrid (std::string filename, DArray< RDFieldDft< D > > const & fields)
Write array of RFieldDft objects (k-space fields) to a file.
This function opens a file with name filename, writes discrete Fourier transform components (DFT) components of fields to that file, and closes the file.
Parameters
filename name of output file.
fields array of RFieldDft fields (k-space grid)
Definition at line 469 of file FieldIo.tpp.
writeFieldHeader()
template<int D>
void Pscf::Pspg::FieldIo< D >::writeFieldHeader (std::ostream & out, int nMonomer) const
Write header for field file (fortran pscf format)
Parameters
out output stream (i.e., output file)
nMonomer number of monomer types
Definition at line 509 of file FieldIo.tpp.
References Pscf::writeUnitCellHeader().
convertBasisToKGrid() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::convertBasisToKGrid (RDField< D > const & components, RDFieldDft< D > & dft)
Convert field from symmetrized basis to Fourier transform (k-grid).
Parameters
components coefficients of symmetry-adapted basis functions
dft discrete Fourier transform of a real field
Definition at line 522 of file FieldIo.tpp.
References Pscf::Basis< D >::Star::beginId, Pscf::Basis< D >::Star::cancel, Pscf::Pspg::DField< cudaReal >::cDField(), Pscf::Pspg::DField< cudaComplex >::cDField(), Pscf::Pspg::RDFieldDft< D >::dftDimensions(), Pscf::Basis< D >::Star::invertFlag, Pscf::Mesh< D >::rank(), Pscf::Mesh< D >::size(), UTIL_CHECK, and UTIL_THROW.
convertBasisToKGrid() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::convertBasisToKGrid (DArray< RDField< D > > & in, DArray< RDFieldDft< D > > & out)
Convert fields from symmetrized basis to Fourier transform (kgrid).
The in and out parameters are arrays of fields, in which element number i is the field associated with monomer type i.
Parameters
in components of fields in symmetry adapted basis
out fields defined as discrete Fourier transforms (k-grid)
Definition at line 759 of file FieldIo.tpp.
References UTIL_ASSERT.
convertKGridToBasis() [1/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::convertKGridToBasis (RDFieldDft< D > const & dft, RDField< D > & components)
Convert field from Fourier transform (k-grid) to symmetrized basis.
Parameters
dft complex DFT (k-grid) representation of a field.
components coefficients of symmetry-adapted basis functions.
Definition at line 649 of file FieldIo.tpp.
References Pscf::Basis< D >::Star::beginId, Pscf::Basis< D >::Star::cancel, Pscf::Pspg::DField< cudaReal >::cDField(), Pscf::Pspg::DField< cudaComplex >::cDField(), Pscf::Pspg::RDFieldDft< D >::dftDimensions(), Pscf::Basis< D >::Star::endId, Pscf::Basis< D >::Star::invertFlag, Pscf::Mesh< D >::rank(), Pscf::Basis< D >::Star::size, UTIL_CHECK, and UTIL_THROW.
convertKGridToBasis() [2/2]
template<int D>
void Pscf::Pspg::FieldIo< D >::convertKGridToBasis (DArray< RDFieldDft< D > > & in, DArray< RDField< D > > & out)
Convert fields from Fourier transform (kgrid) to symmetrized basis.
The in and out parameters are each an array of fields, in which element i is the field associated with monomer type i.
Parameters
in fields defined as discrete Fourier transforms (k-grid)
out components of fields in symmetry adapted basis
Definition at line 854 of file FieldIo.tpp.
References UTIL_ASSERT.
convertBasisToRGrid()
template<int D>
void Pscf::Pspg::FieldIo< D >::convertBasisToRGrid (DArray< RDField< D > > & in, DArray< RDField< D > > & out)
Convert fields from symmetrized basis to spatial grid (rgrid).
Parameters
in fields in symmetry adapted basis form
out fields defined on real-space grid
Definition at line 869 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::deallocate(), and UTIL_ASSERT.
convertRGridToBasis()
template<int D>
void Pscf::Pspg::FieldIo< D >::convertRGridToBasis (DArray< RDField< D > > & in, DArray< RDField< D > > & out)
Convert fields from spatial grid (rgrid) to symmetrized basis.
Parameters
in fields defined on real-space grid
out fields in symmetry adapted basis form
Definition at line 893 of file FieldIo.tpp.
References Util::DArray< Data >::allocate(), Util::DArray< Data >::deallocate(), and UTIL_ASSERT.
The documentation for this class was generated from the following files:
FieldIo.h
FieldIo.tpp