Pscf::Vertex Class Reference
A junction or chain end in a block polymer.
#include <Vertex.h>
Public Member Functions
void setId (int id)
Set the integer identifier of this vertex.
void addBlock (const BlockDescriptor &block)
Add block to the list of attached blocks.
void addBond (const BondDescriptor &bond)
Add bond to the list of attached bonds.
int id () const
Get the id of this vertex.
int size () const
Get the number of attached blocks or bonds.
const Pair< int > & inPropagatorId (int i) const
Get the block/bonds and direction of an incoming propagator.
const Pair< int > & outPropagatorId (int i) const
Get the block/bond and direction of an outgoing propagator.
Detailed Description
A junction or chain end in a block polymer.
Definition at line 26 of file Vertex.h.
Member Function Documentation
setId()
void Pscf::Vertex::setId (int id)
Set the integer identifier of this vertex.
Parameters
id identifier
Definition at line 25 of file Vertex.cpp.
addBlock()
void Pscf::Vertex::addBlock (const BlockDescriptor & block)
Add block to the list of attached blocks.
Preconditions: The id for this vertex must have been set, vertex ids must have been set for the block, and the id of this vertex must match one of the ids for the two vertices attached to the block.
Parameters
block attached BlockDescriptor object
Definition at line 28 of file Vertex.cpp.
References Pscf::BlockDescriptor::id(), UTIL_THROW, and Pscf::BlockDescriptor::vertexId().
addBond()
void Pscf::Vertex::addBond (const BondDescriptor & bond)
Add bond to the list of attached bonds.
Preconditions: The id for this vertex must have been set, vertex ids must have been set for the bond, and the id of this vertex must match one of the ids for the two vertices attached to the bond.
Parameters
bond attached BondDescriptor object
Definition at line 59 of file Vertex.cpp.
References Pscf::BondDescriptor::id(), UTIL_THROW, and Pscf::BondDescriptor::vertexId().
id()
int Pscf::Vertex::id () const [inline]
Get the id of this vertex.
Definition at line 107 of file Vertex.h.
size()
int Pscf::Vertex::size () const [inline]
Get the number of attached blocks or bonds.
Definition at line 110 of file Vertex.h.
Referenced by Pscf::DPolymerTmpl< Bond< D > >::readParameters(), and Pscf::PolymerTmpl< Block< D > >::readParameters().
inPropagatorId()
const Pair< int > & Pscf::Vertex::inPropagatorId (int i) const [inline]
Get the block/bonds and direction of an incoming propagator.
The first element of the integer pair is the block/bond id, and the second is a direction id which is 0 if this vertex is vertex 1 of the block/bond, and 1 if this vertex is vertex 0.
Parameters
i index of incoming propagator
Returns
Pair<int> containing block/bond index, direction index
Definition at line 114 of file Vertex.h.
Referenced by Pscf::DPolymerTmpl< Bond< D > >::readParameters(), and Pscf::PolymerTmpl< Block< D > >::readParameters().
outPropagatorId()
const Pair< int > & Pscf::Vertex::outPropagatorId (int i) const [inline]
Get the block/bond and direction of an outgoing propagator.
The first element of the integer pair is the block/bond id, and the second is a direction id which is 0 if this vertex is vertex 0 of the block/bond, and 1 if this vertex is vertex 1.
Parameters
i index of incoming propagator
Returns
Pair<int> containing block/bond index, direction index
Definition at line 118 of file Vertex.h.
The documentation for this class was generated from the following files:
Vertex.h
Vertex.cpp