Pscf::Interaction Class Reference
Base class for excess free energy models.
#include <Interaction.h>
Public Member Functions
Interaction ()
Constructor.
virtual ~Interaction ()
Destructor.
void setNMonomer (int nMonomer)
Set the number of monomer types.
virtual double fHelmholtz (Array< double > const &c) const =0
Compute excess Helmholtz free energy per monomer.
virtual void computeW (Array< double > const &c, Array< double > &w) const =0
Compute interaction contributions to chemical potentials.
virtual void computeC (Array< double > const &w, Array< double > &c, double &xi) const =0
Compute concentration and xi from chemical potentials.
virtual void computeXi (Array< double > const &w, double &xi) const =0
Compute Langrange multiplier xi from chemical potentials.
virtual void computeDwDc (Array< double > const &c, Matrix< double > &dWdC) const =0
Compute matrix of derivatives of w fields w/ respect to c fields.
int nMonomer () const
Get number of monomer types.
Additional Inherited Members
Detailed Description
Base class for excess free energy models.
Definition at line 25 of file Interaction.h.
Constructor & Destructor Documentation
Interaction()
Pscf::Interaction::Interaction ()
Constructor.
Definition at line 14 of file Interaction.cpp.
References Util::ParamComposite::setClassName().
 Interaction()
Pscf::Interaction::~Interaction () [virtual]
Destructor.
Definition at line 18 of file Interaction.cpp.
Member Function Documentation
setNMonomer()
void Pscf::Interaction::setNMonomer (int nMonomer)
Set the number of monomer types.
Parameters
nMonomer number of monomer types.
Definition at line 21 of file Interaction.cpp.
References nMonomer().
fHelmholtz()
virtual double Pscf::Interaction::fHelmholtz (Array< double > const & c) const [pure virtual]
Compute excess Helmholtz free energy per monomer.
Parameters
c array of concentrations, for each type (input)
Implemented in Pscf::ChiInteraction.
Referenced by Pscf::Homogeneous::Mixture::computeFreeEnergy().
computeW()
virtual void Pscf::Interaction::computeW (Array< double > const & c, Array< double > & w) const [pure virtual]
Compute interaction contributions to chemical potentials.
The resulting chemical potential fields are those obtained with a vanishing Lagrange multiplier / pressure field, xi = 0.
Parameters
c array of concentrations, for each type (input)
w array of chemical potentials, for each type (output)
Implemented in Pscf::ChiInteraction.
Referenced by Pscf::Homogeneous::Mixture::computeMu().
computeC()
virtual void Pscf::Interaction::computeC (Array< double > const & w, Array< double > & c, double & xi) const [pure virtual]
Compute concentration and xi from chemical potentials.
Parameters
w array of chemical potentials, for each type (input)
c array of concentrations, for each type (output)
xi Lagrange multiplier pressure (output)
Implemented in Pscf::ChiInteraction.
computeXi()
virtual void Pscf::Interaction::computeXi (Array< double > const & w, double & xi) const [pure virtual]
Compute Langrange multiplier xi from chemical potentials.
Parameters
w array of chemical potentials, for each type (input)
xi Lagrange multiplier pressure (output)
Implemented in Pscf::ChiInteraction.
computeDwDc()
virtual void Pscf::Interaction::computeDwDc (Array< double > const & c, Matrix< double > & dWdC) const [pure virtual]
Compute matrix of derivatives of w fields w/ respect to c fields.
Upon return, the elements of the matrix dWdC are given by derivatives elements dWdC(i,j) = dW(i)/dC(j), which are also second derivatives of fHelmholtz with respect to concentrations.
Parameters
c array of concentrations, for each type (input)
dWdC square symmetric matrix of derivatives (output)
Implemented in Pscf::ChiInteraction.
Referenced by Pscf::Homogeneous::Mixture::computePhi().
nMonomer()
int Pscf::Interaction::nMonomer () const [inline]
Get number of monomer types.
Definition at line 124 of file Interaction.h.
Referenced by Pscf::ChiInteraction::computeC(), Pscf::ChiInteraction::computeDwDc(), Pscf::Homogeneous::Mixture::computeMu(), Pscf::Homogeneous::Mixture::computePhi(), Pscf::ChiInteraction::computeW(), Pscf::ChiInteraction::computeXi(), Pscf::ChiInteraction::fHelmholtz(), Pscf::ChiInteraction::readParameters(), and setNMonomer().
The documentation for this class was generated from the following files:
Interaction.h
Interaction.cpp