Util::Parameter Class Reference
A single variable in a parameter file.
#include <Parameter.h>
Public Member Functions
Parameter (const char *label, bool isRequired=true)
Constructor.
virtual ~Parameter ()
Destructor.
virtual void readParam (std::istream &in)
Read a label and (if the label matches) a parameter value.
virtual void load (Serializable::IArchive &ar)
Load from an archive.
virtual void save (Serializable::OArchive &ar)
Save to an archive.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Static Public Member Functions
template<class Type >
static void saveOptional (Serializable::OArchive &ar, Type &value, bool isActive)
Save an optional parameter value to an output archive.
template<class Type >
static void saveOptionalCArray (Serializable::OArchive &ar, Type *ptr, int n, bool isActive)
Save an optional C-array of n values to an output archive.
template<class Type >
static void saveOptionalCArray2D (Serializable::OArchive &ar, Type *ptr, int m, int n, int np, bool isActive)
Save an optional two-dimensional C array to an output archive.
Static Public Attributes
static const int Width = 20
Width of output field for a scalar variable.
static const int Precision = 12
Precision for io of floating point data field.
Protected Member Functions
virtual void readValue (std::istream &in)
Read parameter value from an input stream.
virtual void loadValue (Serializable::IArchive &ar)
Load bare parameter value from an archive.
virtual void saveValue (Serializable::OArchive &ar)
Save parameter value to an archive.
virtual void bcastValue ()
Broadcast parameter value within the ioCommunicator.
Protected Attributes
Label label_
Label object that contains parameter label string.
bool isActive_
Is this parameter active (always true if isRequired).
Additional Inherited Members
Detailed Description
A single variable in a parameter file.
Parameter is a base class for objects that read and write the value of a single C++ variable from or to a parameter file. The parameter file format for a parameter contains a string label followed by a value for the variable. Different subclasses of parameter are specialized for different variable types, which can include primitive C/C++ variables, user defined types that overload the << and >> operators, or any of several different types of container.
A Parameter may be required or optional element in a parameter file, depending on the value of the bool isRequired parameter of the constructor. An optional element becomes `active` when an entry with the correct label is read from a parameter file, or when an active value is loaded from an archive. By convention, a required Parameter is always active, even before its value is read or loaded. The bool functions isRequired() and isActive() can be used to query the state of a Parameter.
The overloaded saveOptional() static member functions can be used to save optional parameters to an archive in a form that records whether or not they are active.
Definition at line 45 of file Parameter.h.
Constructor & Destructor Documentation
Parameter()
Util::Parameter::Parameter (const char * label, bool isRequired = true)
Constructor.
Parameters
label label string preceding value in file format
isRequired Is this a required parameter?
Definition at line 22 of file Parameter.cpp.
 Parameter()
Util::Parameter::~Parameter () [virtual]
Destructor.
Definition at line 30 of file Parameter.cpp.
Member Function Documentation
saveOptional()
template<class Type >
void Util::Parameter::saveOptional (Serializable::OArchive & ar, Type & value, bool isActive) [static]
Save an optional parameter value to an output archive.
Parameters
ar output archive to which to save
value reference to value of optional parameter
isActive Is this parameter present in the parameter file?
Definition at line 224 of file Parameter.h.
References isActive().
saveOptionalCArray()
template<class Type >
void Util::Parameter::saveOptionalCArray (Serializable::OArchive & ar, Type * ptr, int n, bool isActive) [static]
Save an optional C-array of n values to an output archive.
Parameters
ar output archive to which to save
ptr pointer to first element of optional C-array parameter
n number of elements in array
isActive Is this parameter present in the parameter file?
Definition at line 237 of file Parameter.h.
References isActive(), and Util::BinaryFileOArchive::pack().
saveOptionalCArray2D()
template<class Type >
void Util::Parameter::saveOptionalCArray2D (Serializable::OArchive & ar, Type * ptr, int m, int n, int np, bool isActive) [static]
Save an optional two-dimensional C array to an output archive.
Parameters
ar output archive to which to save
ptr pointer to first element optional 2D C-array parameter
m logical number of rows in array
n logical number of columns in array
np logical number of columns in array
isActive Is this parameter present in the parameter file?
Definition at line 250 of file Parameter.h.
References isActive(), and Util::BinaryFileOArchive::pack().
readParam()
void Util::Parameter::readParam (std::istream & in) [virtual]
Read a label and (if the label matches) a parameter value.
The parameter file format for a Parameter consists of a label string followed by value. The value is read if and only if the label matches the expected value for this Parameter. If this Parameter is required and the input label not match, an error message is printed to the log file and Exception is thrown. If the Parameter is not required and the input label does not match, the label string is retained in an buffer for later processing by the readParam method of other ParamComponent objects.
Upon entry to this function, a label string is read into a label buffer if and only if the buffer is empty. This buffer is a static member of the Label class, which can retain a label between invocations of the readParameter method of different ParamComponent objects. Once a label string is read from file, it remains in the label buffer until until it is matched, at which point the buffer is cleared to allow processing of the next label.
Parameters
in input stream from which to read
Implements Util::ParamComponent.
Definition at line 36 of file Parameter.cpp.
References Util::bcast< bool >(), bcastValue(), Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::hasIoCommunicator(), Util::ParamComponent::indent(), Util::MpiFileIo::ioCommunicator(), isActive_, Util::MpiFileIo::isIoProcessor(), Util::Label::isMatched(), isRequired(), label_, readValue(), UTIL_THROW, Width, and Util::ParamComponent::writeParam().
load()
void Util::Parameter::load (Serializable::IArchive & ar) [virtual]
Load from an archive.
An optional Parameter loads the value of an isActive flag, and then loads the parameter value only if the isActive is true. A required Parameter simply loads the parameter value. The variable associated with an optional Parameter must be set to its default value before attempting to load the parameter. Optional parameters should be saved either using the save() method of an associated Parameter object or using the appropriate overloaded Parameter::saveOptional() static member function, which both use the required format.
Parameters
ar input archive from which to load
Reimplemented from Util::ParamComponent.
Definition at line 98 of file Parameter.cpp.
References Util::bcast< bool >(), bcastValue(), Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::hasIoCommunicator(), Util::ParamComponent::indent(), Util::MpiFileIo::ioCommunicator(), isActive_, Util::MpiFileIo::isIoProcessor(), isRequired(), label_, loadValue(), UTIL_THROW, Width, and Util::ParamComponent::writeParam().
Referenced by Util::ParamComposite::loadCArray(), Util::ParamComposite::loadCArray2D(), Util::ParamComposite::loadDArray(), Util::ParamComposite::loadDMatrix(), Util::ParamComposite::loadDSymmMatrix(), Util::ParamComposite::loadFArray(), and Util::ParamComposite::loadParameter().
save()
void Util::Parameter::save (Serializable::OArchive & ar) [virtual]
Save to an archive.
An optional Parameter saves the value of the isActive flag, and then saves a parameter value only if the isActive is true. A required Parameter simply saves its value. The label string is not saved to the archive.
The overloaded static saveOptional functions can also be used to save optional parameter values in this format.
Parameters
ar output archive to which to save
Reimplemented from Util::ParamComponent.
Definition at line 145 of file Parameter.cpp.
References isActive_, isRequired(), and saveValue().
label()
std::string Util::Parameter::label () const
Return label string.
Definition at line 158 of file Parameter.cpp.
References label_, and Util::Label::string().
isRequired()
bool Util::Parameter::isRequired () const
Is this an optional parameter?
Definition at line 164 of file Parameter.cpp.
References Util::Label::isRequired(), and label_.
Referenced by load(), readParam(), and save().
isActive()
bool Util::Parameter::isActive () const
Is this parameter active?
Definition at line 170 of file Parameter.cpp.
References isActive_.
Referenced by saveOptional(), saveOptionalCArray(), and saveOptionalCArray2D().
readValue()
virtual void Util::Parameter::readValue (std::istream & in) [inline], [protected], [virtual]
Read parameter value from an input stream.
Parameters
in input stream from which to read
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::DSymmMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 195 of file Parameter.h.
Referenced by readParam().
loadValue()
virtual void Util::Parameter::loadValue (Serializable::IArchive & ar) [inline], [protected], [virtual]
Load bare parameter value from an archive.
Parameters
ar input archive from which to load
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::DSymmMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 202 of file Parameter.h.
Referenced by load().
saveValue()
virtual void Util::Parameter::saveValue (Serializable::OArchive & ar) [inline], [protected], [virtual]
Save parameter value to an archive.
Parameters
ar output archive to which to save
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::DSymmMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 209 of file Parameter.h.
Referenced by save().
bcastValue()
virtual void Util::Parameter::bcastValue () [inline], [protected], [virtual]
Broadcast parameter value within the ioCommunicator.
Reimplemented in Util::ScalarParam< Type >, Util::CArray2DParam< Type >, Util::DMatrixParam< Type >, Util::DSymmMatrixParam< Type >, Util::FArrayParam< Type, N >, Util::DArrayParam< Type >, and Util::CArrayParam< Type >.
Definition at line 215 of file Parameter.h.
Referenced by load(), and readParam().
Member Data Documentation
Width
const int Util::Parameter::Width = 20 [static]
Width of output field for a scalar variable.
Definition at line 53 of file Parameter.h.
Referenced by load(), readParam(), Util::CArrayParam< Type >::writeParam(), Util::DArrayParam< Type >::writeParam(), Util::FArrayParam< Type, N >::writeParam(), Util::DSymmMatrixParam< Type >::writeParam(), Util::DMatrixParam< Type >::writeParam(), Util::ScalarParam< Type >::writeParam(), and Util::CArray2DParam< Type >::writeParam().
Precision
const int Util::Parameter::Precision = 12 [static]
Precision for io of floating point data field.
Definition at line 56 of file Parameter.h.
Referenced by Util::CArrayParam< Type >::writeParam(), Util::DArrayParam< Type >::writeParam(), Util::FArrayParam< Type, N >::writeParam(), Util::DSymmMatrixParam< Type >::writeParam(), Util::DMatrixParam< Type >::writeParam(), Util::ScalarParam< Type >::writeParam(), and Util::CArray2DParam< Type >::writeParam().
label_
Label Util::Parameter::label_ [protected]
Label object that contains parameter label string.
Definition at line 185 of file Parameter.h.
Referenced by isRequired(), label(), load(), pscfpp.ParamComposite.Parameter::read(), readParam(), and pscfpp.ParamComposite.Parameter::setValue().
isActive_
bool Util::Parameter::isActive_ [protected]
Is this parameter active (always true if isRequired).
Definition at line 188 of file Parameter.h.
Referenced by isActive(), load(), readParam(), and save().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cpp