Util::Timer Class Reference
Wall clock timer.
#include <Timer.h>
Public Member Functions
Timer ()
Default constructor.
void start (TimePoint begin)
Start timing from an externally supplied time.
void start ()
Start timing from now (internally computed).
void stop (TimePoint end)
Stop the clock at an externally supplied time.
void stop ()
Stop the clock now (internally supplied).
bool isRunning ()
Is this Timer running?
void clear ()
Reset accumulated time to zero.
double time ()
Return the accumulated time, in seconds.
Static Public Member Functions
static TimePoint now ()
Return current time point.
Detailed Description
Wall clock timer.
A Timer keeps track of the time elapsed during one or more interval. Each interval begins when start() is called and ends when stop() is called. If start() and stop() are invoked repeatedly, the timer accumulates the time elapses in multiple intervals. The accumulated time is returned by the time() method, and can be reset to zero by the clear() method.
Definition at line 34 of file Timer.h.
Constructor & Destructor Documentation
Timer()
Util::Timer::Timer ()
Default constructor.
Constructor.
Definition at line 16 of file Timer.cpp.
References clear().
Member Function Documentation
start() [1/2]
void Util::Timer::start (TimePoint begin) [inline]
Start timing from an externally supplied time.
Set start time and set isRunning = true.
Parameters
begin starting TimePoint.
Definition at line 134 of file Timer.h.
References UTIL_THROW.
Referenced by Pscf::Pspg::Continuous::AmIterator< D >::solve().
start() [2/2]
void Util::Timer::start () [inline]
Start timing from now (internally computed).
Set start time and set isRunning = true.
Definition at line 147 of file Timer.h.
References now(), and UTIL_THROW.
stop() [1/2]
void Util::Timer::stop (TimePoint end) [inline]
Stop the clock at an externally supplied time.
Increment accumulated time, set isRunning = false.
Definition at line 159 of file Timer.h.
References UTIL_THROW.
Referenced by Pscf::Pspg::Continuous::AmIterator< D >::solve().
stop() [2/2]
void Util::Timer::stop () [inline]
Stop the clock now (internally supplied).
Increment accumulated time, set isRunning = false.
Definition at line 175 of file Timer.h.
References now().
isRunning()
bool Util::Timer::isRunning () [inline]
Is this Timer running?
Definition at line 194 of file Timer.h.
clear()
void Util::Timer::clear () [inline]
Reset accumulated time to zero.
Definition at line 181 of file Timer.h.
Referenced by Timer().
time()
double Util::Timer::time ()
Return the accumulated time, in seconds.
Definition at line 23 of file Timer.cpp.
Referenced by Pscf::Pspg::Continuous::AmIterator< D >::solve().
now()
Timer::TimePoint Util::Timer::now () [inline], [static]
Return current time point.
Return current time point (static function)
Definition at line 123 of file Timer.h.
Referenced by Pscf::Pspg::Continuous::AmIterator< D >::solve(), start(), and stop().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp