Pscf::Pspg::Continuous::Propagator< D > Class Template Reference
MDE solver for one-direction of one block.
#include <Propagator.h>
Public Types
typedef RDField< D > Field
Generic field (function of position).
typedef RDField< D > WField
Chemical potential field type.
typedef RDField< D > CField
Monomer concentration field type.
typedef RDField< D > QField
Propagator q-field type.
Public Member Functions
Propagator ()
Constructor.
~Propagator ()
Destructor.
void setBlock (Block< D > &block)
Associate this propagator with a block.
void allocate (int ns, const Mesh< D > &mesh)
Associate this propagator with a block.
void solveForward ()
Compute the forward propagators and store the `slices` for the corresponding block.
void solveBackward (cudaReal *q, int n)
Compute the backward propagators with the stored `slices` as well as the integrals and normalized single chain partition function that are needed for concentration fields and for the corresponding block.
double intQ (cudaReal *q, cudaReal *qs)
Compute and return partition function for the molecule.
const cudaReal * q (int i) const
Return q-field at specified step.
cudaReal * head () const
Return q-field at beginning of block (initial condition).
const cudaReal * qtail () const
Return q-field at end of block.
Block< D > & block ()
Get the associated Block object by reference.
bool isAllocated () const
Has memory been allocated for this propagator?
Protected Member Functions
void computeHead ()
Compute initial QField at head from tail QFields of sources.
Detailed Description
template<int D>
class Pscf::Pspg::Continuous::Propagator< D >
MDE solver for one-direction of one block.
Definition at line 38 of file Propagator.h.
Member Typedef Documentation
Field
template<int D>
typedef RDField<D> Pscf::Pspg::Continuous::Propagator< D >::Field
Generic field (function of position).
Definition at line 48 of file Propagator.h.
WField
template<int D>
typedef RDField<D> Pscf::Pspg::Continuous::Propagator< D >::WField
Chemical potential field type.
Definition at line 54 of file Propagator.h.
CField
template<int D>
typedef RDField<D> Pscf::Pspg::Continuous::Propagator< D >::CField
Monomer concentration field type.
Definition at line 59 of file Propagator.h.
QField
template<int D>
typedef RDField<D> Pscf::Pspg::Continuous::Propagator< D >::QField
Propagator q-field type.
Definition at line 64 of file Propagator.h.
Constructor & Destructor Documentation
Propagator()
template<int D>
Pscf::Pspg::Continuous::Propagator< D >::Propagator
Constructor.
Definition at line 35 of file Propagator.tpp.
 Propagator()
template<int D>
Pscf::Pspg::Continuous::Propagator< D >::~Propagator
Destructor.
Definition at line 47 of file Propagator.tpp.
Member Function Documentation
setBlock()
template<int D>
void Pscf::Pspg::Continuous::Propagator< D >::setBlock (Block< D > & block) [inline]
Associate this propagator with a block.
Parameters
block associated Block object.
Definition at line 269 of file Propagator.h.
allocate()
template<int D>
void Pscf::Pspg::Continuous::Propagator< D >::allocate (int ns, const Mesh< D > & mesh)
Associate this propagator with a block.
Parameters
ns number of contour length steps
mesh spatial discretization mesh
Definition at line 56 of file Propagator.tpp.
References Pscf::Mesh< D >::dimensions(), Pscf::Pspg::ThreadGrid::nBlocks(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), and Pscf::Mesh< D >::size().
solveForward()
template<int D>
void Pscf::Pspg::Continuous::Propagator< D >::solveForward
Compute the forward propagators and store the `slices` for the corresponding block.
Definition at line 121 of file Propagator.tpp.
References UTIL_CHECK.
solveBackward()
template<int D>
void Pscf::Pspg::Continuous::Propagator< D >::solveBackward (cudaReal * q, int n)
Compute the backward propagators with the stored `slices` as well as the integrals and normalized single chain partition function that are needed for concentration fields and for the corresponding block.
Definition at line 223 of file Propagator.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_CHECK.
intQ()
template<int D>
double Pscf::Pspg::Continuous::Propagator< D >::intQ (cudaReal * q, cudaReal * qs)
Compute and return partition function for the molecule.
This function is called by void solveBackward(cudaReal *q, int n)
Definition at line 308 of file Propagator.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical().
q()
template<int D>
const cudaReal * Pscf::Pspg::Continuous::Propagator< D >::q (int i) const [inline]
Return q-field at specified step.
Parameters
i step index
Definition at line 238 of file Propagator.h.
head()
template<int D>
cudaReal * Pscf::Pspg::Continuous::Propagator< D >::head [inline]
Return q-field at beginning of block (initial condition).
Definition at line 205 of file Propagator.h.
qtail()
template<int D>
const cudaReal * Pscf::Pspg::Continuous::Propagator< D >::qtail [inline]
Return q-field at end of block.
Definition at line 229 of file Propagator.h.
block()
template<int D>
Block< D > & Pscf::Pspg::Continuous::Propagator< D >::block [inline]
Get the associated Block object by reference.
Definition at line 253 of file Propagator.h.
isAllocated()
template<int D>
bool Pscf::Pspg::Continuous::Propagator< D >::isAllocated [inline]
Has memory been allocated for this propagator?
Definition at line 260 of file Propagator.h.
computeHead()
template<int D>
void Pscf::Pspg::Continuous::Propagator< D >::computeHead [protected]
Compute initial QField at head from tail QFields of sources.
Definition at line 84 of file Propagator.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_THROW.
The documentation for this class was generated from the following files:
Propagator.h
Propagator.tpp