Pscf::ChiInteraction Class Reference
Flory-Huggins excess free energy model.
#include <ChiInteraction.h>
Public Member Functions
ChiInteraction ()
Constructor.
virtual ~ChiInteraction ()
Destructor.
virtual void readParameters (std::istream &in)
Read chi parameters.
virtual double fHelmholtz (Array< double > const &c) const
Compute excess Helmholtz free energy per monomer.
virtual void computeW (Array< double > const &c, Array< double > &w) const
Compute chemical potential from concentration.
virtual void computeC (Array< double > const &w, Array< double > &c, double &xi) const
Compute concentration from chemical potential fields.
virtual void computeXi (Array< double > const &w, double &xi) const
Compute Langrange multiplier xi from chemical potential fields.
virtual void computeDwDc (Array< double > const &c, Matrix< double > &dWdC) const
Compute second derivatives of free energy.
double chi (int i, int j)
Return one element of the chi matrix.
double chiInverse (int i, int j)
Return one element of the inverse chi matrix.
double idemp (int i, int j)
Return one element of the idempotent matrix.
Additional Inherited Members
Detailed Description
Flory-Huggins excess free energy model.
Definition at line 23 of file ChiInteraction.h.
Constructor & Destructor Documentation
ChiInteraction()
Pscf::ChiInteraction::ChiInteraction ()
Constructor.
Definition at line 18 of file ChiInteraction.cpp.
References Util::ParamComposite::setClassName().
 ChiInteraction()
Pscf::ChiInteraction::~ChiInteraction () [virtual]
Destructor.
Definition at line 25 of file ChiInteraction.cpp.
Member Function Documentation
readParameters()
void Pscf::ChiInteraction::readParameters (std::istream & in) [virtual]
Read chi parameters.
Must be called after setNMonomer.
Reimplemented from Util::ParamComposite.
Definition at line 31 of file ChiInteraction.cpp.
References Pscf::LuSolver::allocate(), Util::DMatrix< Data >::allocate(), Pscf::LuSolver::computeLU(), Pscf::LuSolver::inverse(), Pscf::Interaction::nMonomer(), Util::ParamComposite::readDSymmMatrix(), UTIL_CHECK, and UTIL_THROW.
fHelmholtz()
double Pscf::ChiInteraction::fHelmholtz (Array< double > const & c) const [virtual]
Compute excess Helmholtz free energy per monomer.
Parameters
c array of concentrations, for each type (input)
Implements Pscf::Interaction.
Definition at line 93 of file ChiInteraction.cpp.
References Pscf::Interaction::nMonomer().
computeW()
void Pscf::ChiInteraction::computeW (Array< double > const & c, Array< double > & w) const [virtual]
Compute chemical potential from concentration.
Parameters
c array of concentrations, for each type (input)
w array of chemical potentials for types (ouptut)
Implements Pscf::Interaction.
Definition at line 109 of file ChiInteraction.cpp.
References Pscf::Interaction::nMonomer().
computeC()
void Pscf::ChiInteraction::computeC (Array< double > const & w, Array< double > & c, double & xi) const [virtual]
Compute concentration from chemical potential fields.
Parameters
w array of chemical potentials for types (inut)
c array of vol. fractions, for each type (output)
xi Langrange multiplier pressure (output)
Implements Pscf::Interaction.
Definition at line 125 of file ChiInteraction.cpp.
References Pscf::Interaction::nMonomer().
computeXi()
void Pscf::ChiInteraction::computeXi (Array< double > const & w, double & xi) const [virtual]
Compute Langrange multiplier xi from chemical potential fields.
Parameters
w array of chemical potentials for types (inut)
xi Langrange multiplier pressure (output)
Implements Pscf::Interaction.
Definition at line 151 of file ChiInteraction.cpp.
References Pscf::Interaction::nMonomer().
computeDwDc()
void Pscf::ChiInteraction::computeDwDc (Array< double > const & c, Matrix< double > & dWdC) const [virtual]
Compute second derivatives of free energy.
Upon return, the elements of the square matrix dWdC, are given by derivatives dWdC(i,j) = dW(i)/dC(j), which are also second derivatives of the interaction free energy. For this Flory-Huggins chi parameter model, this is simply given by the chi matrix dWdC(i,j) = chi(i, j).
Parameters
c array of concentrations, for each type (input)
dWdC matrix of derivatives (output)
Implements Pscf::Interaction.
Definition at line 170 of file ChiInteraction.cpp.
References Pscf::Interaction::nMonomer().
chi()
double Pscf::ChiInteraction::chi (int i, int j) [inline]
Return one element of the chi matrix.
Parameters
i row index
j column index
Definition at line 142 of file ChiInteraction.h.
chiInverse()
double Pscf::ChiInteraction::chiInverse (int i, int j) [inline]
Return one element of the inverse chi matrix.
Parameters
i row index
j column index
Definition at line 145 of file ChiInteraction.h.
idemp()
double Pscf::ChiInteraction::idemp (int i, int j) [inline]
Return one element of the idempotent matrix.
Parameters
i row index
j column index
Definition at line 148 of file ChiInteraction.h.
The documentation for this class was generated from the following files:
ChiInteraction.h
ChiInteraction.cpp