Pscf::Pspg::Continuous::Mixture< D > Class Template Reference
Solver for a mixture of polymers and solvents.
#include <Mixture.h>
Public Types
typedef Propagator< D >::WField WField
Monomer chemical potential field type.
typedef Propagator< D >::CField CField
Monomer concentration or volume fraction field type.
Public Member Functions
Mixture ()
Constructor.
~Mixture ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
void setMesh (Mesh< D > const &mesh, UnitCell< D > &unitCell)
Create an association with the mesh and allocate memory.
void setupUnitCell (const UnitCell< D > &unitCell, const WaveList< D > &wavelist)
Set unit cell parameters used in solver.
void compute (DArray< WField > const &wFields, DArray< CField > &cFields)
Compute concentrations.
void computeStress (WaveList< D > &wavelist)
Get monomer reference volume.
double stress (int n)
Get derivative of free energy w/ respect to cell parameter.
double vMonomer () const
Get monomer reference volume.
Protected Member Functions
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Additional Inherited Members
Detailed Description
template<int D>
class Pscf::Pspg::Continuous::Mixture< D >
Solver for a mixture of polymers and solvents.
A Mixture contains a list of Polymer and Solvent objects. Each such object can solve the single-molecule statistical mechanics problem for an ideal gas of the associated species in a set of specified chemical potential fields, and thereby compute concentrations and single-molecule partition functions. A Mixture is thus both a chemistry descriptor and an ideal-gas solver.
A Mixture is associated with a Mesh<D> object, which models a spatial discretization mesh.
Definition at line 50 of file pgc/solvers/Mixture.h.
Member Typedef Documentation
WField
template<int D>
typedef Propagator<D>::WField Pscf::Pspg::Continuous::Mixture< D >::WField
Monomer chemical potential field type.
Definition at line 59 of file pgc/solvers/Mixture.h.
CField
template<int D>
typedef Propagator<D>::CField Pscf::Pspg::Continuous::Mixture< D >::CField
Monomer concentration or volume fraction field type.
Definition at line 64 of file pgc/solvers/Mixture.h.
Constructor & Destructor Documentation
Mixture()
template<int D>
Pscf::Pspg::Continuous::Mixture< D >::Mixture
Constructor.
Definition at line 36 of file Mixture.tpp.
References Util::ParamComposite::setClassName().
 Mixture()
template<int D>
Pscf::Pspg::Continuous::Mixture< D >::~Mixture () [default]
Destructor.
Member Function Documentation
readParameters()
template<int D>
void Pscf::Pspg::Continuous::Mixture< D >::readParameters (std::istream & in) [virtual]
Read all parameters and initialize.
This function reads in a complete description of the chemical composition and structure of all species, as well as the target contour length step size ds.
Parameters
in input parameter stream
Reimplemented from Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >.
Definition at line 48 of file Mixture.tpp.
References UTIL_CHECK.
setMesh()
template<int D>
void Pscf::Pspg::Continuous::Mixture< D >::setMesh (Mesh< D > const & mesh, UnitCell< D > & unitCell)
Create an association with the mesh and allocate memory.
The Mesh<D> object must have already been initialized, e.g., by reading its parameters from a file, so that the mesh dimensions are known on entry.
Parameters
mesh associated Mesh<D> object (stores address).
Definition at line 81 of file Mixture.tpp.
References Pscf::Mesh< D >::dimensions(), Pscf::UnitCellBase< D >::nParameter(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_CHECK.
setupUnitCell()
template<int D>
void Pscf::Pspg::Continuous::Mixture< D >::setupUnitCell (const UnitCell< D > & unitCell, const WaveList< D > & wavelist)
Set unit cell parameters used in solver.
Parameters
unitCell UnitCell<D> object that contains Bravais lattice.
Definition at line 238 of file Mixture.tpp.
References Pscf::MeshIterator< D >::atEnd(), Pscf::MeshIterator< D >::begin(), Pscf::UnitCellBase< D >::ksq(), Pscf::UnitCellBase< D >::nParameter(), Pscf::MeshIterator< D >::position(), Pscf::MeshIterator< D >::rank(), and Pscf::MeshIterator< D >::setDimensions().
compute()
template<int D>
void Pscf::Pspg::Continuous::Mixture< D >::compute (DArray< WField > const & wFields, DArray< CField > & cFields)
Compute concentrations.
This function calls the compute function of every molecular species, and then adds the resulting block concentration fields for blocks of each type to compute a total monomer concentration (or volume fraction) for each monomer type. Upon return, values are set for volume fraction and chemical potential (mu) members of each species, and for the concentration fields for each Block and Solvent. The total concentration for each monomer type is returned in the cFields output parameter.
The arrays wFields and cFields must each have size nMonomer(), and contain fields that are indexed by monomer type index.
Parameters
wFields array of chemical potential fields (input)
cFields array of monomer concentration fields (output)
Definition at line 335 of file Mixture.tpp.
References Pscf::Pspg::DField< Data >::cDField(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_CHECK.
computeStress()
template<int D>
void Pscf::Pspg::Continuous::Mixture< D >::computeStress (WaveList< D > & wavelist)
Get monomer reference volume.
Definition at line 408 of file Mixture.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical().
stress()
template<int D>
double Pscf::Pspg::Continuous::Mixture< D >::stress (int n) [inline]
Get derivative of free energy w/ respect to cell parameter.
Get precomputed value of derivative of free energy per monomer with respect to unit cell parameter number n.
\int n unit cell parameter id
Definition at line 158 of file pgc/solvers/Mixture.h.
vMonomer()
template<int D>
double Pscf::Pspg::Continuous::Mixture< D >::vMonomer [inline]
Get monomer reference volume.
Definition at line 267 of file pgc/solvers/Mixture.h.
read()
template<int D>
template<typename Type >
ScalarParam< Type > & Util::ParamComposite::read (typename Type) [protected]
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 1156 of file ParamComposite.h.
readOptional()
template<int D>
template<typename Type >
ScalarParam< Type > & Util::ParamComposite::readOptional (typename Type) [inline], [protected]
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 1164 of file ParamComposite.h.
The documentation for this class was generated from the following files:
pgc/solvers/Mixture.h
Mixture.tpp