Pscf::Pspg::Continuous::System< D > Class Template Reference
Main class in SCFT simulation of one system.
#include <System.h>
Public Types
typedef RDField< D > Field
Base class for WField and CField.
typedef Propagator< D >::WField WField
Monomer chemical potential field type.
typedef Propagator< D >::CField CField
Monomer concentration / volume fraction field type.
Public Member Functions
System ()
Constructor.
~System ()
Destructor.
 Lifetime (Actions)
void setOptions (int argc, char **argv)
Process command line options.
void setOptionsOutside (char *pArg, char *cArg, bool echo, int s=1)
virtual void readParam (std::istream &in)
Read input parameters (with opening and closing lines).
void readParam ()
Read input parameters from default param file.
virtual void readParameters (std::istream &in)
Read body of input parameters block (without opening and closing lines).
void readCommands (std::istream &in)
Read command script.
void readCommands ()
Read commands from default command file.
void readCommandsJson (int=1)
Read commands from json-format command file.
void readCommandsJson (std::string filename, int s)
void iterate ()
void computeFreeEnergy ()
Compute free energy density and pressure for current fields.
void outputThermo (std::ostream &out)
Output the thermodynamic properties to a file.
void outputThermo (Json::Value &thermo)
void fieldIO (std::string io, std::string type, std::string format, std::string dir, std::string caseid, std::string prefix)
 Chemical Potential Fields (W Fields)
DArray< Field > & wFields ()
Get an array of chemical potential fields, in a basis.
Field & wField (int monomerId)
Get chemical potential field for one monomer type, in a basis.
DArray< WField > & wFieldsRGrid ()
Get array of chemical potential fields, on an r-space grid.
DArray< RDField< D > > & wFieldsRGridPh ()
WField & wFieldRGrid (int monomerId)
Get the chemical potential field for one monomer type, on a grid.
RDField< D > & wFieldRGridPh (int monomerId)
DArray< RDFieldDft< D > > & wFieldsKGrid ()
Get array of chemical potential fields, in Fourier space.
RDFieldDft< D > & wFieldKGrid (int monomerId)
Get the chemical potential field for one monomer, in Fourier space.
 Monomer Concentration / Volume Fraction Fields (C Fields)
DArray< Field > & cFields ()
Get an array of all monomer concentration fields, in a basis.
Field & cField (int monomerId)
Get the concentration field for one monomer type, in a basis.
DArray< CField > & cFieldsRGrid ()
Get array of all concentration fields (c fields), on a grid.
DArray< CField > & cFieldsRGridPh ()
CField & cFieldRGrid (int monomerId)
Get the concentration (c field) for one monomer type, on a grid.
CField & cFieldRGridPh (int monomerId)
DArray< RDFieldDft< D > > & cFieldsKGrid ()
Get all monomer concentration fields, in Fourier space (k-grid).
RDFieldDft< D > & cFieldKGrid (int monomerId)
Get the c field for one monomer type, in Fourier space (k-grid).
double c (int monomerId)
return homogeneous volume fraction for one monnomer type.
 Accessors (access objects by reference)
int systemId ()
Mixture< D > & mixture ()
Get Mixture by reference.
Mesh< D > & mesh ()
Get spatial discretization mesh by reference.
UnitCell< D > & unitCell ()
Get crystal unitCell (i.e., lattice type and parameters) by reference.
ChiInteraction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
AmIterator< D > & iterator ()
Get the Iterator by reference.
Basis< D > & basis ()
Get basis object by reference.
WaveList< D > & wavelist ()
Get container for wavevector data.
FieldIo< D > & fieldIo ()
Get associated FieldIo object.
FFT< D > & fft ()
Get associated FFT object by reference.
FCT< D > & fct ()
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
Accessors (return values)
std::string groupName ()
Get the group name string.
double fHelmholtz () const
Get precomputed Helmholtz free energy per monomer / kT.
double pressure () const
Get precomputed pressure x monomer volume kT.
bool hasWFields () const
Have monomer chemical potential fields (w fields) been set?
bool hasCFields () const
Have monomer concentration fields (c fields) been computed?
Detailed Description
template<int D>
class Pscf::Pspg::Continuous::System< D >
Main class in SCFT simulation of one system.
Definition at line 22 of file pgc/iterator/Iterator.h.
Member Typedef Documentation
Field
template<int D>
typedef RDField<D> Pscf::Pspg::Continuous::System< D >::Field
Base class for WField and CField.
Definition at line 55 of file pgc/System.h.
WField
template<int D>
typedef Propagator<D>::WField Pscf::Pspg::Continuous::System< D >::WField
Monomer chemical potential field type.
Definition at line 58 of file pgc/System.h.
CField
template<int D>
typedef Propagator<D>::CField Pscf::Pspg::Continuous::System< D >::CField
Monomer concentration / volume fraction field type.
Definition at line 61 of file pgc/System.h.
Constructor & Destructor Documentation
System()
template<int D>
Pscf::Pspg::Continuous::System< D >::System
Constructor.
Definition at line 46 of file pgc/System.tpp.
References Pscf::Pspg::ThreadGrid::init().
 System()
template<int D>
Pscf::Pspg::Continuous::System< D >::~System
Destructor.
Definition at line 79 of file pgc/System.tpp.
Member Function Documentation
setOptions()
template<int D>
void Pscf::Pspg::Continuous::System< D >::setOptions (int argc, char ** argv)
Process command line options.
Definition at line 91 of file pgc/System.tpp.
References Util::Log::file(), Util::ParamComponent::setEcho(), Pscf::Pspg::ThreadGrid::setThreadsPerBlock(), and UTIL_THROW.
readParam() [1/2]
template<int D>
void Pscf::Pspg::Continuous::System< D >::readParam (std::istream & in) [virtual]
Read input parameters (with opening and closing lines).
Parameters
in input parameter stream
Definition at line 215 of file pgc/System.tpp.
readParam() [2/2]
template<int D>
void Pscf::Pspg::Continuous::System< D >::readParam
Read input parameters from default param file.
Definition at line 203 of file pgc/System.tpp.
readParameters()
template<int D>
void Pscf::Pspg::Continuous::System< D >::readParameters (std::istream & in) [virtual]
Read body of input parameters block (without opening and closing lines).
Parameters
in input parameter stream
Read crystallographic unit cell (used only to create basis)
Definition at line 226 of file pgc/System.tpp.
readCommands() [1/2]
template<int D>
void Pscf::Pspg::Continuous::System< D >::readCommands (std::istream & in)
Read command script.
Parameters
in command script file.
Definition at line 928 of file pgc/System.tpp.
References Util::Log::file(), and UTIL_CHECK.
readCommands() [2/2]
template<int D>
void Pscf::Pspg::Continuous::System< D >::readCommands
Read commands from default command file.
Definition at line 913 of file pgc/System.tpp.
References UTIL_THROW.
readCommandsJson()
template<int D>
void Pscf::Pspg::Continuous::System< D >::readCommandsJson (int s = 1)
Read commands from json-format command file.
Definition at line 466 of file pgc/System.tpp.
References UTIL_THROW.
computeFreeEnergy()
template<int D>
void Pscf::Pspg::Continuous::System< D >::computeFreeEnergy
Compute free energy density and pressure for current fields.
This function should be called after a successful call of iterator().solve(). Resulting values are returned by the freeEnergy() and pressure() accessor functions.
Definition at line 1458 of file pgc/System.tpp.
References Pscf::PolymerTmpl< Block< D > >::length(), Pscf::Species::mu(), Pscf::Pspg::ThreadGrid::nBlocks(), Pscf::Pspg::ThreadGrid::nThreads(), Pscf::Species::phi(), and Pscf::Pspg::ThreadGrid::setThreadsLogical().
outputThermo()
template<int D>
void Pscf::Pspg::Continuous::System< D >::outputThermo (std::ostream & out)
Output the thermodynamic properties to a file.
This function outputs Helmholtz free energy per monomer, pressure (in units of kT per monomer volume), and the volume fraction and chemical potential of each species.
/param out
Definition at line 1600 of file pgc/System.tpp.
wFields()
template<int D>
DArray< RDField< D > > & Pscf::Pspg::Continuous::System< D >::wFields [inline]
Get an array of chemical potential fields, in a basis.
This function returns an array in which each element is an array containing the coefficients of the chemical potential field (w field) in a symmetry-adapted basis for one monomer type. The array capacity is the number of monomer types.
Definition at line 676 of file pgc/System.h.
wField()
template<int D>
RDField< D > & Pscf::Pspg::Continuous::System< D >::wField (int monomerId) [inline]
Get chemical potential field for one monomer type, in a basis.
This function returns an array containing coefficients of the chemical potential field (w field) in a symmetry-adapted basis for a specified monomer type.
Parameters
monomerId integer monomer type index
Definition at line 683 of file pgc/System.h.
wFieldsRGrid()
template<int D>
DArray< typename System< D >::WField > & Pscf::Pspg::Continuous::System< D >::wFieldsRGrid [inline]
Get array of chemical potential fields, on an r-space grid.
This function returns an array in which each element is a WField object containing values of the chemical potential field (w field) on a regular grid for one monomer type. The array capacity is the number of monomer types.
Definition at line 690 of file pgc/System.h.
wFieldRGrid()
template<int D>
System< D >::WField & Pscf::Pspg::Continuous::System< D >::wFieldRGrid (int monomerId) [inline]
Get the chemical potential field for one monomer type, on a grid.
Parameters
monomerId integer monomer type index
Definition at line 705 of file pgc/System.h.
wFieldsKGrid()
template<int D>
DArray< RDFieldDft< D > > & Pscf::Pspg::Continuous::System< D >::wFieldsKGrid [inline]
Get array of chemical potential fields, in Fourier space.
The array capacity is equal to the number of monomer types.
Definition at line 717 of file pgc/System.h.
wFieldKGrid()
template<int D>
RDFieldDft< D > & Pscf::Pspg::Continuous::System< D >::wFieldKGrid (int monomerId) [inline]
Get the chemical potential field for one monomer, in Fourier space.
Parameters
monomerId integer monomer type index
Definition at line 723 of file pgc/System.h.
cFields()
template<int D>
DArray< RDField< D > > & Pscf::Pspg::Continuous::System< D >::cFields [inline]
Get an array of all monomer concentration fields, in a basis.
This function returns an array in which each element is an array containing the coefficients of the monomer concentration field (cfield) for one monomer type in a symmetry-adapted basis. The array capacity is equal to the number of monomer types.
Definition at line 730 of file pgc/System.h.
cField()
template<int D>
RDField< D > & Pscf::Pspg::Continuous::System< D >::cField (int monomerId) [inline]
Get the concentration field for one monomer type, in a basis.
This function returns an array containing the coefficients of the monomer concentration / volume fraction field (c field) for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 737 of file pgc/System.h.
cFieldsRGrid()
template<int D>
DArray< typename System< D >::CField > & Pscf::Pspg::Continuous::System< D >::cFieldsRGrid [inline]
Get array of all concentration fields (c fields), on a grid.
This function returns an array in which each element is the monomer concentration field for one monomer type on a regular grid (an r-grid).
Definition at line 744 of file pgc/System.h.
cFieldRGrid()
template<int D>
System< D >::CField & Pscf::Pspg::Continuous::System< D >::cFieldRGrid (int monomerId) [inline]
Get the concentration (c field) for one monomer type, on a grid.
Parameters
monomerId integer monomer type index
Definition at line 753 of file pgc/System.h.
cFieldsKGrid()
template<int D>
DArray< RDFieldDft< D > > & Pscf::Pspg::Continuous::System< D >::cFieldsKGrid [inline]
Get all monomer concentration fields, in Fourier space (k-grid).
This function returns an array in which each element is the discrete Fourier transform (DFT) of the concentration field (c field) for on monomer type.
Definition at line 759 of file pgc/System.h.
cFieldKGrid()
template<int D>
RDFieldDft< D > & Pscf::Pspg::Continuous::System< D >::cFieldKGrid (int monomerId) [inline]
Get the c field for one monomer type, in Fourier space (k-grid).
This function returns the discrete Fourier transform (DFT) of the concentration field (c field) for monomer type index monomerId.
Parameters
monomerId integer monomer type index
Definition at line 765 of file pgc/System.h.
c()
template<int D>
double Pscf::Pspg::Continuous::System< D >::c (int monomerId) [inline]
return homogeneous volume fraction for one monnomer type.
Definition at line 771 of file pgc/System.h.
mixture()
template<int D>
Mixture< D > & Pscf::Pspg::Continuous::System< D >::mixture [inline]
Get Mixture by reference.
Definition at line 590 of file pgc/System.h.
mesh()
template<int D>
Mesh< D > & Pscf::Pspg::Continuous::System< D >::mesh [inline]
Get spatial discretization mesh by reference.
Definition at line 597 of file pgc/System.h.
unitCell()
template<int D>
UnitCell< D > & Pscf::Pspg::Continuous::System< D >::unitCell [inline]
Get crystal unitCell (i.e., lattice type and parameters) by reference.
Definition at line 604 of file pgc/System.h.
interaction()
template<int D>
ChiInteraction & Pscf::Pspg::Continuous::System< D >::interaction [inline]
Get interaction (i.e., excess free energy model) by reference.
Definition at line 611 of file pgc/System.h.
References UTIL_ASSERT.
iterator()
template<int D>
AmIterator< D > & Pscf::Pspg::Continuous::System< D >::iterator [inline]
Get the Iterator by reference.
Definition at line 654 of file pgc/System.h.
References UTIL_ASSERT.
basis()
template<int D>
Basis< D > & Pscf::Pspg::Continuous::System< D >::basis [inline]
Get basis object by reference.
Definition at line 632 of file pgc/System.h.
References UTIL_ASSERT.
wavelist()
template<int D>
WaveList< D > & Pscf::Pspg::Continuous::System< D >::wavelist [inline]
Get container for wavevector data.
Definition at line 640 of file pgc/System.h.
fieldIo()
template<int D>
FieldIo< D > & Pscf::Pspg::Continuous::System< D >::fieldIo [inline]
Get associated FieldIo object.
Definition at line 647 of file pgc/System.h.
fft()
template<int D>
FFT< D > & Pscf::Pspg::Continuous::System< D >::fft [inline]
Get associated FFT object by reference.
Definition at line 619 of file pgc/System.h.
homogeneous()
template<int D>
Homogeneous::Mixture & Pscf::Pspg::Continuous::System< D >::homogeneous [inline]
Get homogeneous mixture (for reference calculations).
Definition at line 662 of file pgc/System.h.
fileMaster()
template<int D>
FileMaster & Pscf::Pspg::Continuous::System< D >::fileMaster [inline]
Get FileMaster by reference.
Definition at line 669 of file pgc/System.h.
groupName()
template<int D>
std::string Pscf::Pspg::Continuous::System< D >::groupName [inline]
Get the group name string.
Definition at line 778 of file pgc/System.h.
fHelmholtz()
template<int D>
double Pscf::Pspg::Continuous::System< D >::fHelmholtz [inline]
Get precomputed Helmholtz free energy per monomer / kT.
The value retrieved by this function is computed by the computeFreeEnergy() function.
Definition at line 785 of file pgc/System.h.
pressure()
template<int D>
double Pscf::Pspg::Continuous::System< D >::pressure [inline]
Get precomputed pressure x monomer volume kT.
The value retrieved by this function is computed by the computeFreeEnergy() function.
Definition at line 792 of file pgc/System.h.
hasWFields()
template<int D>
bool Pscf::Pspg::Continuous::System< D >::hasWFields [inline]
Have monomer chemical potential fields (w fields) been set?
A true value is returned if and only if values have been set on a real space grid. The READ_W_BASIS command must immediately convert from a basis to a grid to satisfy this requirement.
Definition at line 799 of file pgc/System.h.
hasCFields()
template<int D>
bool Pscf::Pspg::Continuous::System< D >::hasCFields [inline]
Have monomer concentration fields (c fields) been computed?
A true value is returned if and only if monomer concentration fields have been computed by solving the modified diffusion equation for the current w fields, and values are known on a grid (cFieldsRGrid).
Definition at line 806 of file pgc/System.h.
The documentation for this class was generated from the following files:
pgc/iterator/Iterator.h
pgc/System.h
pgc/System.tpp