Pscf::Homogeneous::Molecule Class Reference
Descriptor of a molecular species in a homogeneous mixture.
#include <Molecule.h>
Public Member Functions
Molecule ()
Constructor.
~Molecule ()
Destructor.
virtual void readParameters (std::istream &in)
Read and initialize.
void setNClump (int nClump)
Set the number of clumps, and allocate memory.
void computeSize ()
Compute total molecule size by adding clump sizes.
Accessors
Clump & clump (int id)
Get a specified Clump.
const Clump & clump (int id) const
Get a specified Clump.
int nClump () const
Number of monomer clumps (monomer types).
double size () const
Total molecule size = volume / reference volume.
Additional Inherited Members
Detailed Description
Descriptor of a molecular species in a homogeneous mixture.
A Homogeneous::Molecule has:
An array of Homogeneous::Clump objects
An overall size (volume/monomer volume)
Each Clump has a monomer type id and a size. The size is the total volume of monomers of that type in a molecule of this species.
Definition at line 38 of file Molecule.h.
Constructor & Destructor Documentation
Molecule()
Pscf::Homogeneous::Molecule::Molecule ()
Constructor.
Definition at line 15 of file Molecule.cpp.
References Util::ParamComposite::setClassName().
 Molecule()
Pscf::Homogeneous::Molecule::~Molecule ()
Destructor.
Definition at line 25 of file Molecule.cpp.
Member Function Documentation
readParameters()
void Pscf::Homogeneous::Molecule::readParameters (std::istream & in) [virtual]
Read and initialize.
Call either this or setNClump to initialize, not both.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 31 of file Molecule.cpp.
References UTIL_ASSERT.
setNClump()
void Pscf::Homogeneous::Molecule::setNClump (int nClump)
Set the number of clumps, and allocate memory.
Call either this or readParameters to initialize, not both. If this is used to allocate memory, all clump properties must be set using Clump::setMonomerId() and Clump::setSize().
Definition at line 47 of file Molecule.cpp.
References UTIL_ASSERT.
computeSize()
void Pscf::Homogeneous::Molecule::computeSize ()
Compute total molecule size by adding clump sizes.
Definition at line 58 of file Molecule.cpp.
References UTIL_ASSERT.
clump() [1/2]
Homogeneous::Clump & Pscf::Homogeneous::Molecule::clump (int id) [inline]
Get a specified Clump.
Parameters
id clump index, 0 <= id < nClump
Definition at line 141 of file Molecule.h.
Referenced by Pscf::Homogeneous::Mixture::computeMu(), Pscf::Homogeneous::Mixture::computePhi(), and Pscf::Homogeneous::Mixture::validate().
clump() [2/2]
const Homogeneous::Clump & Pscf::Homogeneous::Molecule::clump (int id) const [inline]
Get a specified Clump.
Parameters
id clump index, 0 <= id < nClump
Definition at line 147 of file Molecule.h.
nClump()
int Pscf::Homogeneous::Molecule::nClump () const [inline]
Number of monomer clumps (monomer types).
Definition at line 126 of file Molecule.h.
Referenced by Pscf::Homogeneous::Mixture::computeMu(), Pscf::Homogeneous::Mixture::computePhi(), and Pscf::Homogeneous::Mixture::validate().
size()
double Pscf::Homogeneous::Molecule::size () const [inline]
Total molecule size = volume / reference volume.
Definition at line 132 of file Molecule.h.
References UTIL_CHECK.
Referenced by Pscf::Homogeneous::Mixture::computeMu(), and Pscf::Homogeneous::Mixture::computePhi().
The documentation for this class was generated from the following files:
Molecule.h
Molecule.cpp