Util::AutoCorr< Data, Product > Class Template Reference
Auto-correlation function for one sequence of Data values.
#include <AutoCorr.h>
Public Member Functions
AutoCorr ()
Constructor.
~AutoCorr ()
Destructor.
void clear ()
Reset to empty state.
void readParameters (std::istream &in)
Read buffer capacity, allocate memory and initialize.
void setParam (int bufferCapacity)
Set buffer capacity, allocate memory and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from an archive.
virtual void save (Serializable::OArchive &ar)
Save state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
void sample (Data value)
Sample a value.
void output (std::ostream &out)
Output the autocorrelation function.
int bufferCapacity () const
Return capacity of history buffer.
int nSample () const
Return number of values sampled thus far.
Data average () const
Return average of all sampled values.
double corrTime () const
Numerical integration of autocorrelation function.
Product autoCorrelation (int t) const
Return autocorrelation at a given lag time.
Additional Inherited Members
Detailed Description
template<typename Data, typename Product>
class Util::AutoCorr< Data, Product >
Auto-correlation function for one sequence of Data values.
This class calculates an autocorrelation function for a sequence x(i) of values of a variable or object of type Data. The resulting autocorrelation function is and array of values of type Product, where C(j) = <x(i-j), x(i)>. Here <A,B> denotes an inner product of type Product for objects A and B of type Data.
The meaning of the inner product is defined for various data types b the overloaded function Product product(Data, Data) that is defined for double, complex and Vector data in the product.h file.
The zero value for variables of type Data is returned by the overloaded function void setToZero(Data) method defined in the setToData.h file.
Definition at line 49 of file AutoCorr.h.
Constructor & Destructor Documentation
AutoCorr()
template<typename Data , typename Product >
Util::AutoCorr< Data, Product >::AutoCorr
Constructor.
Definition at line 183 of file AutoCorr.h.
References Util::ParamComposite::setClassName(), and Util::setToZero().
 AutoCorr()
template<typename Data , typename Product >
Util::AutoCorr< Data, Product >::~AutoCorr
Destructor.
Definition at line 198 of file AutoCorr.h.
Member Function Documentation
clear()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::clear
Reset to empty state.
Definition at line 247 of file AutoCorr.h.
References Util::setToZero().
readParameters()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::readParameters (std::istream & in) [virtual]
Read buffer capacity, allocate memory and initialize.
Parameters
in input parameter stream.
Reimplemented from Util::ParamComposite.
Definition at line 205 of file AutoCorr.h.
setParam()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::setParam (int bufferCapacity)
Set buffer capacity, allocate memory and initialize.
Parameters
bufferCapacity maximum number of values in history buffer.
Definition at line 215 of file AutoCorr.h.
loadParameters()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::loadParameters (Serializable::IArchive & ar) [virtual]
Load state from an archive.
Parameters
ar binary loading (input) archive.
Reimplemented from Util::ParamComposite.
Definition at line 225 of file AutoCorr.h.
save()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::save (Serializable::OArchive & ar) [virtual]
Save state to an archive.
Parameters
ar binary saving (output) archive.
Reimplemented from Util::ParamComposite.
Definition at line 240 of file AutoCorr.h.
serialize()
template<typename Data , typename Product >
template<class Archive >
void Util::AutoCorr< Data, Product >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 419 of file AutoCorr.h.
sample()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::sample (Data value)
Sample a value.
Parameters
value current value
Definition at line 295 of file AutoCorr.h.
References Util::product().
output()
template<typename Data , typename Product >
void Util::AutoCorr< Data, Product >::output (std::ostream & out)
Output the autocorrelation function.
Parameters
out output stream.
Definition at line 335 of file AutoCorr.h.
References Util::product().
bufferCapacity()
template<typename Data , typename Product >
int Util::AutoCorr< Data, Product >::bufferCapacity
Return capacity of history buffer.
Definition at line 310 of file AutoCorr.h.
nSample()
template<typename Data , typename Product >
int Util::AutoCorr< Data, Product >::nSample
Return number of values sampled thus far.
Definition at line 317 of file AutoCorr.h.
average()
template<typename Data , typename Product >
Data Util::AutoCorr< Data, Product >::average
Return average of all sampled values.
Definition at line 324 of file AutoCorr.h.
corrTime()
template<typename Data , typename Product >
double Util::AutoCorr< Data, Product >::corrTime
Numerical integration of autocorrelation function.
Definition at line 361 of file AutoCorr.h.
References Util::product(), and Util::setToZero().
autoCorrelation()
template<typename Data , typename Product >
Product Util::AutoCorr< Data, Product >::autoCorrelation (int t) const
Return autocorrelation at a given lag time.
Parameters
t the lag time
Definition at line 395 of file AutoCorr.h.
References Util::product().
The documentation for this class was generated from the following file:
AutoCorr.h