Pscf::BondDescriptor Class Reference
A linear bond (including block-bond and joint-bond) within a block copolymer.
#include <BondDescriptor.h>
Public Member Functions
BondDescriptor ()
Constructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
 Setters
void setId (int id)
Set the id for this block.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
virtual void setLength (int N)
Set the length of this bond.
Accessors (getters)
int id () const
Get the id of this bond.
int monomerId (int i) const
Get the monomer type id at vertex i.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
int length () const
Get the number of segments in this bond.
bool bondtype () const
Get the type of this bond.
bool hasJointSegment () const
std::istream & operator>> (std::istream &in, BondDescriptor &bond)
istream extractor for a BlockDescriptor.
std::ostream & operator<< (std::ostream &out, const BondDescriptor &bond)
Detailed Description
A linear bond (including block-bond and joint-bond) within a block copolymer.
(discrete chain)
Definition at line 19 of file BondDescriptor.h.
Constructor & Destructor Documentation
BondDescriptor()
Pscf::BondDescriptor::BondDescriptor ()
Constructor.
Definition at line 11 of file BondDescriptor.cpp.
Member Function Documentation
serialize()
template<class Archive >
void Pscf::BondDescriptor::serialize (Archive & ar, unsigned int versionId)
Serialize to/from archive.
Parameters
ar input or output Archive
versionId archive format version index
Definition at line 204 of file BondDescriptor.h.
setId()
void Pscf::BondDescriptor::setId (int id)
Set the id for this block.
Parameters
id integer index for this bond
Definition at line 20 of file BondDescriptor.cpp.
References id().
setVertexIds()
void Pscf::BondDescriptor::setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
Parameters
vertexAId integer id of vertex A
vertexBId integer id of vertex B
Definition at line 26 of file BondDescriptor.cpp.
setLength()
void Pscf::BondDescriptor::setLength (int N) [virtual]
Set the length of this bond.
The `length` is the number of segments on this bond.
Parameters
length block length (number of monomers).
Definition at line 35 of file BondDescriptor.cpp.
id()
int Pscf::BondDescriptor::id () const [inline]
Get the id of this bond.
Definition at line 156 of file BondDescriptor.h.
Referenced by Pscf::Vertex::addBond(), and setId().
monomerId()
int Pscf::BondDescriptor::monomerId (int i) const [inline]
Get the monomer type id at vertex i.
Definition at line 163 of file BondDescriptor.h.
vertexIds()
const Pair< int > & Pscf::BondDescriptor::vertexIds () const [inline]
Get the pair of associated vertex ids.
Definition at line 171 of file BondDescriptor.h.
vertexId()
int Pscf::BondDescriptor::vertexId (int i) const [inline]
Get id of an associated vertex.
Parameters
i index of vertex (0 or 1)
Definition at line 178 of file BondDescriptor.h.
Referenced by Pscf::Vertex::addBond().
length()
int Pscf::BondDescriptor::length () const [inline]
Get the number of segments in this bond.
For a block bond, the return value should be a positive integer number.
Definition at line 185 of file BondDescriptor.h.
bondtype()
bool Pscf::BondDescriptor::bondtype () const [inline]
Get the type of this bond.
true for block-bond; false for joint-bond
Definition at line 193 of file BondDescriptor.h.
Friends And Related Function Documentation
operator>>
std::istream& operator>> (std::istream & in, BondDescriptor & bond) [friend]
istream extractor for a BlockDescriptor.
Parameters
in input stream
bond BondDescriptor to be read from stream
Returns
modified input stream
Definition at line 41 of file BondDescriptor.cpp.
The documentation for this class was generated from the following files:
BondDescriptor.h
BondDescriptor.cpp