Util::AutoCorrArray< Data, Product > Class Template Reference
Auto-correlation function for an ensemble of sequences.
#include <AutoCorrArray.h>
Public Member Functions
AutoCorrArray ()
Default constructor.
~AutoCorrArray ()
Default destructor.
virtual void readParameters (std::istream &in)
Read parameters, allocate memory and clear history.
void setParam (int ensembleCapacity, int bufferCapacity)
Allocate memory, and clear history.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setNEnsemble (int nEnsemble)
Set actual number of sequences in ensemble.
void clear ()
Reset to empty state.
void sample (const Array< Data > &values)
Sample an array of current values.
void output (std::ostream &out)
Output the autocorrelation function.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this AutoCorrArray to/from an archive.
int bufferCapacity () const
Return maximum number of samples in history for each sequence.
int nEnsemble () const
Return nEnsemble.
int nSample () const
Return the total number of samples per sequence thus far.
Data average () const
Return average of sampled values.
double corrTime () const
Numerical integral of autocorrelation function.
Additional Inherited Members
Detailed Description
template<typename Data, typename Product>
class Util::AutoCorrArray< Data, Product >
Auto-correlation function for an ensemble of sequences.
This class calculates an autocorrelation function for a ensemble of statistically equivalent sequences x(i) of values of a variable of type Data. The resulting autocorrelation function is an array of values of type Product, where C(j) = <x(i-j), x(i)>. Here <A,B> denotes an inner product of type Product for objects A and B of type Data.
The meaning of <A,B> for two Data values is defined for various data types by the overloaded functions product(Data, Data) defined in file `product.h` . These functions define a product as an arithmetic product for floating point numbers, and use the following definitions for complex numbers and Vector objects:
double  product(double, double)   = A*B
complex product(complex, complex) = conjug(A)*B
double  product(Vector,  Vector)  = A.dot(B)
The meaning of setting a variable to zero is defined for various types of data by the overloaded functions setToZero(Data&) that are defined in file setToZero.h.
Definition at line 57 of file AutoCorrArray.h.
Constructor & Destructor Documentation
AutoCorrArray()
template<typename Data , typename Product >
Util::AutoCorrArray< Data, Product >::AutoCorrArray
Default constructor.
Definition at line 205 of file AutoCorrArray.h.
References Util::ParamComposite::setClassName(), and Util::setToZero().
 AutoCorrArray()
template<typename Data , typename Product >
Util::AutoCorrArray< Data, Product >::~AutoCorrArray
Default destructor.
Definition at line 222 of file AutoCorrArray.h.
Member Function Documentation
readParameters()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::readParameters (std::istream & in) [virtual]
Read parameters, allocate memory and clear history.
Reads parameters ensembleCapacity and bufferCapacity, allocates memory, sets nEnsemble=ensembleCapacity, and calls clear().
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 229 of file AutoCorrArray.h.
setParam()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::setParam (int ensembleCapacity, int bufferCapacity)
Allocate memory, and clear history.
Sets parameters ensembleCapacity and bufferCapacity, allocates memory, sets nEnsemble=ensembleCapacity, and calls clear().
Parameters
ensembleCapacity maximum number of sequences in ensemble
bufferCapacity maximum number of values in each history
Definition at line 241 of file AutoCorrArray.h.
loadParameters()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 253 of file AutoCorrArray.h.
save()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 269 of file AutoCorrArray.h.
setNEnsemble()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::setNEnsemble (int nEnsemble)
Set actual number of sequences in ensemble.
Precondition
readParam() or setParam() must have been called previously
nEnsemble <= ensembleCapacity
Parameters
nEnsemble actual number of sequences in ensemble
Definition at line 276 of file AutoCorrArray.h.
References UTIL_THROW.
clear()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::clear
Reset to empty state.
Definition at line 291 of file AutoCorrArray.h.
References Util::setToZero().
sample()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::sample (const Array< Data > & values)
Sample an array of current values.
Parameters
values Array of current values
Definition at line 331 of file AutoCorrArray.h.
References Util::product().
output()
template<typename Data , typename Product >
void Util::AutoCorrArray< Data, Product >::output (std::ostream & out)
Output the autocorrelation function.
Definition at line 386 of file AutoCorrArray.h.
serialize()
template<typename Data , typename Product >
template<class Archive >
void Util::AutoCorrArray< Data, Product >::serialize (Archive & ar, const unsigned int version)
Serialize this AutoCorrArray to/from an archive.
Parameters
ar input or output archive
version file version id
Definition at line 436 of file AutoCorrArray.h.
bufferCapacity()
template<typename Data , typename Product >
int Util::AutoCorrArray< Data, Product >::bufferCapacity
Return maximum number of samples in history for each sequence.
Definition at line 354 of file AutoCorrArray.h.
nEnsemble()
template<typename Data , typename Product >
int Util::AutoCorrArray< Data, Product >::nEnsemble
Return nEnsemble.
Definition at line 361 of file AutoCorrArray.h.
nSample()
template<typename Data , typename Product >
int Util::AutoCorrArray< Data, Product >::nSample
Return the total number of samples per sequence thus far.
Definition at line 368 of file AutoCorrArray.h.
average()
template<typename Data , typename Product >
Data Util::AutoCorrArray< Data, Product >::average
Return average of sampled values.
Definition at line 375 of file AutoCorrArray.h.
corrTime()
template<typename Data , typename Product >
double Util::AutoCorrArray< Data, Product >::corrTime
Numerical integral of autocorrelation function.
Definition at line 407 of file AutoCorrArray.h.
References Util::product(), and Util::setToZero().
The documentation for this class was generated from the following file:
AutoCorrArray.h