Pscf::Pspg::Continuous::Block< D > Class Template Reference
Block within a branched polymer.
#include <Block.h>
Public Types
typedef Pscf::Pspg::Continuous::Propagator< D >::Field Field
Generic field (base class)
typedef Pscf::Pspg::Continuous::Propagator< D >::WField WField
Monomer chemical potential field.
typedef Pscf::Pspg::Continuous::Propagator< D >::QField QField
Constrained partition function q(r,s) for fixed s.
Public Member Functions
Block ()
Constructor.
~Block ()
Destructor.
void setDiscretization (double ds, const Mesh< D > &mesh)
Initialize discretization and allocate required memory.
void setupUnitCell (const UnitCell< D > &unitCell, const WaveList< D > &wavelist)
Setup parameters that depend on the unit cell.
void setupSolver (WField const &w)
Set solver for this block.
void setupFFT ()
Initialize FFT and batch FFT classes.
void step (const cudaReal *q, cudaReal *qNew)
Compute step of integration loop, from i to i+1.
void computeStress (double prefactor)
Compute derivatives of free energy with respect to cell parameters.
void computeInt (cudaReal *q, cudaReal *qs, int ic)
Compute the integral using RI-K while the backword propagtors are being computed from `slices`.
double stress (int n)
Get derivative of free energy with respect to a unit cell parameter.
const Mesh< D > & mesh () const
Return associated spatial Mesh by reference.
double ds () const
Contour length step size.
int ns () const
Number of contour length steps.
FFT< D > & fft ()
Return the fast Fourier transform object by reference.
int id () const
Get the id of this block.
double length () const
Get the length (number of monomers) in this block.
int monomerId () const
Get the monomer type id.
void setId (int id)
Set the id for this block.
virtual void setLength (double length)
Set the length of this block.
void setMonomerId (int monomerId)
Set the monomer id.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
int vertexId (int i) const
Get id of an associated vertex.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
Detailed Description
template<int D>
class Pscf::Pspg::Continuous::Block< D >
Block within a branched polymer.
(Continuous Gaussian chain)
Derived from BlockTmpl< Propagator<D> >. A BlockTmpl< Propagator<D> > has two Propagator<D> members and is derived from BlockDescriptor.
Definition at line 48 of file Block.h.
Member Typedef Documentation
Field
template<int D>
typedef Pscf::Pspg::Continuous::Propagator<D>::Field Pscf::Pspg::Continuous::Block< D >::Field
Generic field (base class)
Definition at line 55 of file Block.h.
WField
template<int D>
typedef Pscf::Pspg::Continuous::Propagator<D>::WField Pscf::Pspg::Continuous::Block< D >::WField
Monomer chemical potential field.
Definition at line 60 of file Block.h.
QField
template<int D>
typedef Pscf::Pspg::Continuous::Propagator<D>::QField Pscf::Pspg::Continuous::Block< D >::QField
Constrained partition function q(r,s) for fixed s.
Definition at line 65 of file Block.h.
Constructor & Destructor Documentation
Block()
template<int D>
Pscf::Pspg::Continuous::Block< D >::Block
Constructor.
Definition at line 328 of file Block.tpp.
References Pscf::BlockTmpl< Propagator< D > >::propagator().
 Block()
template<int D>
Pscf::Pspg::Continuous::Block< D >::~Block
Destructor.
Definition at line 341 of file Block.tpp.
Member Function Documentation
setDiscretization()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::setDiscretization (double ds, const Mesh< D > & mesh)
Initialize discretization and allocate required memory.
Parameters
ds desired (optimal) value for contour length step
mesh spatial discretization mesh
Definition at line 407 of file Block.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical(), Pscf::Mesh< D >::size(), and UTIL_CHECK.
setupUnitCell()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::setupUnitCell (const UnitCell< D > & unitCell, const WaveList< D > & wavelist)
Setup parameters that depend on the unit cell.
Parameters
unitCell unit cell, defining cell dimensions
waveList container for properties of recip wavevectors
Definition at line 689 of file Block.tpp.
References Pscf::MeshIterator< D >::atEnd(), Pscf::MeshIterator< D >::begin(), Pscf::UnitCellBase< D >::dksq(), Pscf::UnitCellBase< D >::ksq(), Pscf::UnitCellBase< D >::nParameter(), Pscf::MeshIterator< D >::position(), Pscf::MeshIterator< D >::rank(), and Pscf::MeshIterator< D >::setDimensions().
setupSolver()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::setupSolver (WField const & w)
Set solver for this block.
Parameters
w chemical potential field for this monomer type
Definition at line 858 of file Block.tpp.
References Pscf::Pspg::DField< Data >::cDField(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_CHECK.
setupFFT()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::setupFFT
Initialize FFT and batch FFT classes.
Definition at line 899 of file Block.tpp.
step()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::step (const cudaReal * q, cudaReal * qNew)
Compute step of integration loop, from i to i+1.
Apply pseudo-spectral algorithm
Definition at line 943 of file Block.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_CHECK.
computeStress()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::computeStress (double prefactor)
Compute derivatives of free energy with respect to cell parameters.
Parameters
waveList container for properties of recip. latt. wavevectors.
prefactor prefactor = exp(mu_)/length(), where mu_ and length() is the chemical potential and chain length of the corresponding polymer, respectively.
Definition at line 1181 of file Block.tpp.
computeInt()
template<int D>
void Pscf::Pspg::Continuous::Block< D >::computeInt (cudaReal * q, cudaReal * qs, int ic)
Compute the integral using RI-K while the backword propagtors are being computed from `slices`.
Parameters
q Foward propagator.
qs Backward propagtor.
ic Coefficient given by RI-K method.
Definition at line 1201 of file Block.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical(), and UTIL_CHECK.
stress()
template<int D>
double Pscf::Pspg::Continuous::Block< D >::stress (int n) [inline]
Get derivative of free energy with respect to a unit cell parameter.
Parameters
n unit cell parameter index
Definition at line 336 of file Block.h.
mesh()
template<int D>
const Mesh< D > & Pscf::Pspg::Continuous::Block< D >::mesh [inline]
Return associated spatial Mesh by reference.
Get Mesh by reference.
Definition at line 343 of file Block.h.
References UTIL_ASSERT.
ds()
template<int D>
double Pscf::Pspg::Continuous::Block< D >::ds [inline]
Contour length step size.
Get number of contour steps.
Definition at line 329 of file Block.h.
ns()
template<int D>
int Pscf::Pspg::Continuous::Block< D >::ns [inline]
Number of contour length steps.
Get number of contour steps.
Definition at line 322 of file Block.h.
fft()
template<int D>
FFT< D > & Pscf::Pspg::Continuous::Block< D >::fft [inline]
Return the fast Fourier transform object by reference.
Definition at line 350 of file Block.h.
id()
template<int D>
int Pscf::BlockDescriptor::id [inline]
Get the id of this block.
Definition at line 156 of file BlockDescriptor.h.
length()
template<int D>
double Pscf::BlockDescriptor::length [inline]
Get the length (number of monomers) in this block.
Definition at line 180 of file BlockDescriptor.h.
monomerId()
template<int D>
int Pscf::BlockDescriptor::monomerId [inline]
Get the monomer type id.
Definition at line 162 of file BlockDescriptor.h.
setId()
template<int D>
void Pscf::BlockDescriptor::setId
Set the id for this block.
Parameters
id integer index for this block
Definition at line 26 of file BlockDescriptor.cpp.
setLength()
template<int D>
void Pscf::BlockDescriptor::setLength
Set the length of this block.
The `length` is steric volume / reference volume.
Parameters
length block length (number of monomers).
Definition at line 47 of file BlockDescriptor.cpp.
setMonomerId()
template<int D>
void Pscf::BlockDescriptor::setMonomerId
Set the monomer id.
Parameters
monomerId integer id of monomer type (>=0)
Definition at line 41 of file BlockDescriptor.cpp.
setVertexIds()
template<int D>
void Pscf::BlockDescriptor::setVertexIds
Set indices of associated vertices.
Parameters
vertexAId integer id of vertex A
vertexBId integer id of vertex B
Definition at line 32 of file BlockDescriptor.cpp.
vertexId()
template<int D>
int Pscf::BlockDescriptor::vertexId [inline]
Get id of an associated vertex.
Parameters
i index of vertex (0 or 1)
Definition at line 174 of file BlockDescriptor.h.
vertexIds()
template<int D>
const Pair< int > & Pscf::BlockDescriptor::vertexIds [inline]
Get the pair of associated vertex ids.
Definition at line 168 of file BlockDescriptor.h.
The documentation for this class was generated from the following files:
Block.h
Block.tpp