Pscf::Pspg::RDField< D > Class Template Reference
Field of real single precision values on an FFT mesh on a device.
#include <RDField.h>
Public Member Functions
RDField ()
Default constructor.
RDField (RDField< D > const &other)
Copy constructor.
virtual ~RDField ()
Destructor.
RDField & operator= (RDField< D > const &other)
Assignment operator.
void allocate (const IntVec< D > &meshDimensions)
Allocate the underlying C array for an FFT grid.
const IntVec< D > & meshDimensions () const
Return mesh dimensions by constant reference.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Additional Inherited Members
Detailed Description
template<int D>
class Pscf::Pspg::RDField< D >
Field of real single precision values on an FFT mesh on a device.
cudaReal = float
Definition at line 33 of file RDField.h.
Constructor & Destructor Documentation
RDField() [1/2]
template<int D>
Pscf::Pspg::RDField< D >::RDField
Default constructor.
Definition at line 22 of file RDField.tpp.
RDField() [2/2]
template<int D>
Pscf::Pspg::RDField< D >::RDField (RDField< D > const & other)
Copy constructor.
Allocates new memory and copies all elements by value.
uses memcpy! slow!
Parameters
other the RField to be copied.
Definition at line 41 of file RDField.tpp.
References Pscf::Pspg::DField< cudaReal >::capacity_, Pscf::Pspg::DField< cudaReal >::cDField(), Pscf::Pspg::DField< cudaReal >::data_, Pscf::Pspg::DField< cudaReal >::isAllocated(), and UTIL_THROW.
 RDField()
template<int D>
Pscf::Pspg::RDField< D >::~RDField [virtual]
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 30 of file RDField.tpp.
Member Function Documentation
operator=()
template<int D>
RDField< D > & Pscf::Pspg::RDField< D >::operator= (RDField< D > const & other)
Assignment operator.
If this Field is not allocated, launch a kernel to swap memory.
If this and the other Field are both allocated, the capacities must be exactly equal. If so, this method copies all elements.
uses memcpy! slow!
Parameters
other the RHS RField
Definition at line 67 of file RDField.tpp.
References Pscf::Pspg::DField< cudaReal >::capacity(), Pscf::Pspg::DField< cudaReal >::capacity_, Pscf::Pspg::DField< cudaReal >::cDField(), Pscf::Pspg::DField< cudaReal >::isAllocated(), and UTIL_THROW.
allocate()
template<int D>
void Pscf::Pspg::RDField< D >::allocate (const IntVec< D > & meshDimensions)
Allocate the underlying C array for an FFT grid.
Exceptions
Exception if the RField is already allocated.
Parameters
meshDimensions vector containing number of grid points in each direction
Definition at line 109 of file RDField.h.
References Pscf::Pspg::DField< Data >::allocate(), and UTIL_CHECK.
Referenced by Pscf::Pspg::Continuous::AmIterator< D >::minimizeCoeff().
meshDimensions()
template<int D>
const IntVec< D > & Pscf::Pspg::RDField< D >::meshDimensions [inline]
Return mesh dimensions by constant reference.
Definition at line 124 of file RDField.h.
Referenced by Pscf::Pspg::FFT< D >::setup(), and Pscf::Pspg::FFTBatched< D >::setup().
serialize()
template<int D>
template<class Archive >
void Pscf::Pspg::RDField< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Temporarily uses a memcpy
Parameters
ar archive
version archive version id
Definition at line 132 of file RDField.h.
References UTIL_THROW.
The documentation for this class was generated from the following files:
RDField.h
RDField.tpp