CommandLine Class Reference
Abstraction of a C array of command line arguments.
#include <CommandLine.h>
Public Member Functions
CommandLine ()
Constructor.
void append (const char *arg)
Add a command line argument string.
void clear ()
Clear all arguments.
int argc ()
Return number of command line arguments.
char ** argv ()
Return array of C-string command line argument strings.
Detailed Description
Abstraction of a C array of command line arguments.
Definition at line 21 of file CommandLine.h.
Constructor & Destructor Documentation
CommandLine()
CommandLine::CommandLine () [inline]
Constructor.
Definition at line 29 of file CommandLine.h.
References clear().
Member Function Documentation
append()
void CommandLine::append (const char * arg) [inline]
Add a command line argument string.
Definition at line 35 of file CommandLine.h.
Referenced by clear().
clear()
void CommandLine::clear () [inline]
Clear all arguments.
Definition at line 41 of file CommandLine.h.
References append().
Referenced by CommandLine().
argc()
int CommandLine::argc () [inline]
Return number of command line arguments.
Definition at line 54 of file CommandLine.h.
argv()
char** CommandLine::argv () [inline]
Return array of C-string command line argument strings.
Returns
pointer to C array of null terminated C strings.
Definition at line 62 of file CommandLine.h.
The documentation for this class was generated from the following file:
CommandLine.h