Pscf::Pspg::Continuous::AmIterator< D > Class Template Reference
Anderson mixing iterator for the pseudo spectral method.
#include <AmIterator.h>
Public Member Functions
AmIterator ()
Default constructor.
AmIterator (System< D > *system)
Constructor.
~AmIterator ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
void allocate ()
Allocate all arrays.
int solve ()
Iterate to a solution.
double epsilon ()
Getter for epsilon.
int maxHist ()
Getter for the maximum number of field histories to convolute into a new field.
int maxItr ()
Getter for the maximum number of iteration before convergence.
void computeDeviation ()
Compute the deviation of wFields from a mean field solution.
bool isConverged (int itr)
Compute the error from deviations of wFields and compare with epsilon_.
int minimizeCoeff (int itr)
Determine the coefficients that would minimize invertMatrix_ Umn.
void buildOmega (int itr)
Rebuild wFields for the next iteration from minimized coefficients.
Additional Inherited Members
Detailed Description
template<int D>
class Pscf::Pspg::Continuous::AmIterator< D >
Anderson mixing iterator for the pseudo spectral method.
Definition at line 36 of file pgc/iterator/AmIterator.h.
Constructor & Destructor Documentation
AmIterator() [1/2]
template<int D>
Pscf::Pspg::Continuous::AmIterator< D >::AmIterator
Default constructor.
Definition at line 28 of file pgc/iterator/AmIterator.tpp.
References Util::ParamComposite::setClassName().
AmIterator() [2/2]
template<int D>
Pscf::Pspg::Continuous::AmIterator< D >::AmIterator (System< D > * system) [explicit]
Constructor.
Parameters
system pointer to a system object
Definition at line 40 of file pgc/iterator/AmIterator.tpp.
References Util::ParamComposite::setClassName().
 AmIterator()
template<int D>
Pscf::Pspg::Continuous::AmIterator< D >::~AmIterator
Destructor.
Definition at line 52 of file pgc/iterator/AmIterator.tpp.
Member Function Documentation
readParameters()
template<int D>
void Pscf::Pspg::Continuous::AmIterator< D >::readParameters (std::istream & in) [virtual]
Read all parameters and initialize.
Parameters
in input filestream
Reimplemented from Util::ParamComposite.
Definition at line 59 of file pgc/iterator/AmIterator.tpp.
allocate()
template<int D>
void Pscf::Pspg::Continuous::AmIterator< D >::allocate
Allocate all arrays.
Definition at line 69 of file pgc/iterator/AmIterator.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical().
solve()
template<int D>
int Pscf::Pspg::Continuous::AmIterator< D >::solve [virtual]
Iterate to a solution.
Implements Pscf::Pspg::Continuous::Iterator< D >.
Definition at line 118 of file pgc/iterator/AmIterator.tpp.
References Util::Log::file(), Util::Timer::now(), Util::Timer::start(), Util::Timer::stop(), and Util::Timer::time().
epsilon()
template<int D>
double Pscf::Pspg::Continuous::AmIterator< D >::epsilon [inline]
Getter for epsilon.
Definition at line 196 of file pgc/iterator/AmIterator.h.
maxHist()
template<int D>
int Pscf::Pspg::Continuous::AmIterator< D >::maxHist [inline]
Getter for the maximum number of field histories to convolute into a new field.
Definition at line 202 of file pgc/iterator/AmIterator.h.
maxItr()
template<int D>
int Pscf::Pspg::Continuous::AmIterator< D >::maxItr [inline]
Getter for the maximum number of iteration before convergence.
Definition at line 208 of file pgc/iterator/AmIterator.h.
computeDeviation()
template<int D>
void Pscf::Pspg::Continuous::AmIterator< D >::computeDeviation
Compute the deviation of wFields from a mean field solution.
Definition at line 343 of file pgc/iterator/AmIterator.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical().
isConverged()
template<int D>
bool Pscf::Pspg::Continuous::AmIterator< D >::isConverged (int itr)
Compute the error from deviations of wFields and compare with epsilon_.
Returns
true for error < epsilon and false for error >= epsilon
Definition at line 523 of file pgc/iterator/AmIterator.tpp.
References Util::Log::file().
minimizeCoeff()
template<int D>
int Pscf::Pspg::Continuous::AmIterator< D >::minimizeCoeff (int itr)
Determine the coefficients that would minimize invertMatrix_ Umn.
Definition at line 586 of file pgc/iterator/AmIterator.tpp.
References Pscf::LuSolver::allocate(), Pscf::Pspg::RDField< D >::allocate(), Pscf::Pspg::DField< cudaReal >::cDField(), Pscf::LuSolver::computeLU(), Pscf::Pspg::DField< cudaReal >::deallocate(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), and Pscf::LuSolver::solve().
buildOmega()
template<int D>
void Pscf::Pspg::Continuous::AmIterator< D >::buildOmega (int itr)
Rebuild wFields for the next iteration from minimized coefficients.
Definition at line 791 of file pgc/iterator/AmIterator.tpp.
References Pscf::Pspg::ThreadGrid::setThreadsLogical().
The documentation for this class was generated from the following files:
pgc/iterator/AmIterator.h
pgc/iterator/AmIterator.tpp