Crystallography
Classes that describe crystallographic information.
Classes
class Pscf::Basis< D >
Symmetry-adapted basis for pseudo-spectral scft.
class Pscf::SpaceGroup< D >
Crystallographic space group.
class Pscf::SpaceSymmetry< D >
A SpaceSymmetry represents a crystallographic space group symmetry.
struct Pscf::TWave< D >
Simple wave struct for use within Basis construction.
struct Pscf::TWaveNormComp< D >
Comparator for TWave objects, based on TWave::sqNorm.
struct Pscf::TWaveDftComp< D >
Comparator for TWave objects, based on TWave::indicesDft.
struct Pscf::TWaveBzComp< D >
Comparator for TWave objects, based on TWave::indicesBz.
class Pscf::UnitCell< D >
Base template for UnitCell<D> classes, D=1, 2 or 3.
class Pscf::UnitCell< 1 >
1D crystal unit cell.
class Pscf::UnitCell< 2 >
2D crystal unit cell.
class Pscf::UnitCell< 3 >
3D crystal unit cell.
class Pscf::UnitCellBase< D >
Base class template for a crystallographic unit cell.
Functions
std::string Pscf::makeGroupFileName (int D, std::string groupName)
Generates the file name from a group name.
template<int D>
std::ostream & Pscf::operator<< (std::ostream &out, const SpaceGroup< D > &g)
Output stream inserter operator for a SpaceGroup<D>.
template<int D>
std::istream & Pscf::operator>> (std::istream &in, SpaceGroup< D > &g)
Input stream extractor operator for a SpaceGroup<D>.
template<int D>
bool Pscf::operator== (const SpaceSymmetry< D > &A, const SpaceSymmetry< D > &B)
Are two SpaceSymmetry objects equivalent?
template<int D>
bool Pscf::operator!= (const SpaceSymmetry< D > &A, const SpaceSymmetry< D > &B)
Are two SpaceSymmetry objects not equivalent?
template<int D>
SpaceSymmetry< D > Pscf::operator* (const SpaceSymmetry< D > &A, const SpaceSymmetry< D > &B)
Return the product A*B of two symmetry objects.
template<int D>
IntVec< D > Pscf::operator* (const SpaceSymmetry< D > &S, const IntVec< D > &V)
Return the IntVec<D> product S*V of a rotation matrix and an IntVec<D>.
template<int D>
IntVec< D > Pscf::operator* (const IntVec< D > &V, const SpaceSymmetry< D > &S)
Return the IntVec<D> product V*S of an IntVec<D> and a rotation matrix.
template<int D>
std::ostream & Pscf::operator<< (std::ostream &out, const SpaceSymmetry< D > &A)
Output stream inserter for a SpaceSymmetry<D>
template<int D>
std::istream & Pscf::operator>> (std::istream &in, SpaceSymmetry< D > &A)
Input stream extractor for a SpaceSymmetry<D>
template<int D>
std::istream & Pscf::operator>> (std::istream &in, UnitCell< D > &cell)
istream input extractor for a UnitCell<D>.
template<int D>
std::ostream & Pscf::operator<< (std::ostream &out, UnitCell< D > const &cell)
ostream output inserter for a UnitCell<D>.
template<class Archive , int D>
void Pscf::serialize (Archive &ar, UnitCell< D > &cell, const unsigned int version)
Serialize to/from an archive.
template<int D>
void Pscf::readUnitCellHeader (std::istream &in, UnitCell< D > &cell)
Read UnitCell<D> from a field file header (fortran pscf format).
template<int D>
void Pscf::writeUnitCellHeader (std::ostream &out, UnitCell< D > const &cell)
Write UnitCell<D> to a field file header (fortran pscf format).
std::istream & Pscf::operator>> (std::istream &in, UnitCell< 1 >::LatticeSystem &lattice)
istream extractor for a 1D UnitCell<1>::LatticeSystem.
std::ostream & Pscf::operator<< (std::ostream &out, UnitCell< 1 >::LatticeSystem lattice)
ostream inserter for a 1D UnitCell<1>::LatticeSystem.
std::istream & Pscf::operator>> (std::istream &in, UnitCell< 2 >::LatticeSystem &lattice)
istream extractor for a 2D UnitCell<2>::LatticeSystem.
std::istream & Pscf::operator>> (std::istream &in, UnitCell< 3 >::LatticeSystem &lattice)
istream extractor for a 3D UnitCell<3>::LatticeSystem.
std::ostream & Pscf::operator<< (std::ostream &out, UnitCell< 3 >::LatticeSystem lattice)
ostream inserter for an 3D UnitCell<3>::LatticeSystem.
Detailed Description
Classes that describe crystallographic information.
Function Documentation
makeGroupFileName()
std::string Pscf::makeGroupFileName (int D, std::string groupName)
Generates the file name from a group name.
Parameters
groupName standard name of space group
D dimensionality of space (D=1,2 or 3)
groupName standard name of space group
Definition at line 25 of file groupFile.cpp.
References UTIL_THROW.
Referenced by Pscf::Basis< D >::makeBasis().
operator<<() [1/5]
template<int D>
std::ostream& Pscf::operator<< (std::ostream & out, const SpaceGroup< D > & g)
Output stream inserter operator for a SpaceGroup<D>.
Parameters
out output stream
g space group
Definition at line 106 of file SpaceGroup.h.
References Pscf::SymmetryGroup< SpaceSymmetry< D > >::size().
operator>>() [1/6]
template<int D>
std::istream& Pscf::operator>> (std::istream & in, SpaceGroup< D > & g)
Input stream extractor operator for a SpaceGroup<D>.
Parameters
in input stream
g space group
Definition at line 127 of file SpaceGroup.h.
References Pscf::SymmetryGroup< SpaceSymmetry< D > >::add(), Pscf::SymmetryGroup< SpaceSymmetry< D > >::clear(), and UTIL_CHECK.
operator==()
template<int D>
bool Pscf::operator== (const SpaceSymmetry< D > & A, const SpaceSymmetry< D > & B)
Are two SpaceSymmetry objects equivalent?
Parameters
A first symmetry
B second symmetry
Returns
True if A == B, false otherwise
Definition at line 357 of file SpaceSymmetry.h.
operator!=()
template<int D>
bool Pscf::operator!= (const SpaceSymmetry< D > & A, const SpaceSymmetry< D > & B) [inline]
Are two SpaceSymmetry objects not equivalent?
Parameters
A first symmetry
B second symmetry
Returns
True if A != B, false otherwise
Definition at line 305 of file SpaceSymmetry.h.
operator*() [1/3]
template<int D>
SpaceSymmetry< D > Pscf::operator* (const SpaceSymmetry< D > & A, const SpaceSymmetry< D > & B)
Return the product A*B of two symmetry objects.
Parameters
A first symmetry
B second symmetry
Returns
product A*B
Definition at line 378 of file SpaceSymmetry.h.
References Pscf::SpaceSymmetry< D >::normalize().
operator*() [2/3]
template<int D>
IntVec< D > Pscf::operator* (const SpaceSymmetry< D > & S, const IntVec< D > & V)
Return the IntVec<D> product S*V of a rotation matrix and an IntVec<D>.
The product is defined to be the matrix product of the rotation matrix and the integer vector S.R * V.
Parameters
S symmetry operation
V integer vector
Returns
product S*V
Definition at line 411 of file SpaceSymmetry.h.
operator*() [3/3]
template<int D>
IntVec< D > Pscf::operator* (const IntVec< D > & V, const SpaceSymmetry< D > & S)
Return the IntVec<D> product V*S of an IntVec<D> and a rotation matrix.
The product is defined to be the matrix product of the integer vector and the space group rotation matrix S.R * V.
Parameters
V integer vector
S symmetry operation
Returns
product V*S
Definition at line 428 of file SpaceSymmetry.h.
operator<<() [2/5]
template<int D>
std::ostream & Pscf::operator<< (std::ostream & out, const SpaceSymmetry< D > & A)
Output stream inserter for a SpaceSymmetry<D>
Parameters
out output stream
A SpaceSymmetry<D> object to be output
Returns
modified output stream
Definition at line 445 of file SpaceSymmetry.h.
operator>>() [2/6]
template<int D>
std::istream & Pscf::operator>> (std::istream & in, SpaceSymmetry< D > & A)
Input stream extractor for a SpaceSymmetry<D>
Parameters
in input stream
A SpaceSymmetry<D> object to be input
Returns
modified input stream
Definition at line 465 of file SpaceSymmetry.h.
operator>>() [3/6]
template<int D>
std::istream & Pscf::operator>> (std::istream & in, UnitCell< D > & cell)
istream input extractor for a UnitCell<D>.
Parameters
in input stream
cell UnitCell<D> to be read
Returns
modified input stream
Definition at line 21 of file UnitCell.tpp.
References Pscf::UnitCellBase< D >::nParameter_, Pscf::UnitCellBase< D >::parameters_, and Pscf::UnitCellBase< D >::setLattice().
operator<<() [3/5]
template<int D>
std::ostream & Pscf::operator<< (std::ostream & out, UnitCell< D > const & cell)
ostream output inserter for a UnitCell<D>.
Parameters
out output stream
cell UnitCell<D> to be written
Returns
modified output stream
Definition at line 34 of file UnitCell.tpp.
References Pscf::UnitCellBase< D >::nParameter_, and Pscf::UnitCellBase< D >::parameters_.
serialize()
template<class Archive , int D>
void Pscf::serialize (Archive & ar, UnitCell< D > & cell, const unsigned int version)
Serialize to/from an archive.
Parameters
ar input or output archive
cell UnitCell<D> object to be serialized
version archive version id
Definition at line 48 of file UnitCell.tpp.
References Pscf::UnitCellBase< D >::nParameter_, Pscf::UnitCellBase< D >::parameters_, and Util::serializeEnum().
readUnitCellHeader()
template<int D>
void Pscf::readUnitCellHeader (std::istream & in, UnitCell< D > & cell)
Read UnitCell<D> from a field file header (fortran pscf format).
If the unit cell has a non-null lattice system on entry, the value read from file must match this existing value, or this function throws an exception. If the lattice system is null on entry, the lattice system value is read from file. In either case, unit cell parameters (dimensions and angles) are updated using values read from file.
Parameters
in input stream
cell UnitCell<D> to be read
Definition at line 59 of file UnitCell.tpp.
References Pscf::UnitCellBase< D >::nParameter_, Pscf::UnitCellBase< D >::parameters_, Pscf::UnitCellBase< D >::setLattice(), and UTIL_CHECK.
writeUnitCellHeader()
template<int D>
void Pscf::writeUnitCellHeader (std::ostream & out, UnitCell< D > const & cell)
Write UnitCell<D> to a field file header (fortran pscf format).
Parameters
out output stream
cell UnitCell<D> to be written
Definition at line 88 of file UnitCell.tpp.
References Pscf::UnitCellBase< D >::nParameter_, and Pscf::UnitCellBase< D >::parameters_.
Referenced by Pscf::Pspg::FieldIo< D >::writeFieldHeader().
operator>>() [4/6]
std::istream & Pscf::operator>> (std::istream & in, UnitCell< 1 >::LatticeSystem & lattice)
istream extractor for a 1D UnitCell<1>::LatticeSystem.
Parameters
in input stream
lattice UnitCell<1>::LatticeSystem to be read
Returns
modified input stream
Definition at line 52 of file UnitCell1.cpp.
References UTIL_THROW.
operator<<() [4/5]
std::ostream & Pscf::operator<< (std::ostream & out, UnitCell< 1 >::LatticeSystem lattice)
ostream inserter for a 1D UnitCell<1>::LatticeSystem.
Parameters
out output stream
lattice UnitCell<1>::LatticeSystem to be written
Returns
modified output stream
Definition at line 69 of file UnitCell1.cpp.
References UTIL_THROW.
operator>>() [5/6]
std::istream & Pscf::operator>> (std::istream & in, UnitCell< 2 >::LatticeSystem & lattice)
istream extractor for a 2D UnitCell<2>::LatticeSystem.
Parameters
in input stream
lattice UnitCell<2>::LatticeSystem to be read
Returns
modified input stream
Definition at line 157 of file UnitCell2.cpp.
References UTIL_THROW.
operator>>() [6/6]
std::istream & Pscf::operator>> (std::istream & in, UnitCell< 3 >::LatticeSystem & lattice)
istream extractor for a 3D UnitCell<3>::LatticeSystem.
Parameters
in input stream
lattice UnitCell<3>::LatticeSystem to be read
Returns
modified input stream
Definition at line 330 of file UnitCell3.cpp.
References UTIL_THROW.
operator<<() [5/5]
std::ostream & Pscf::operator<< (std::ostream & out, UnitCell< 3 >::LatticeSystem lattice)
ostream inserter for an 3D UnitCell<3>::LatticeSystem.
Parameters
out output stream
lattice UnitCell<3>::LatticeSystem to be written
Returns
modified output stream
Definition at line 365 of file UnitCell3.cpp.
References UTIL_THROW.