Pscf Namespace Reference
Classes for polymer self-consistent field theory.
Namespaces
 Pspg
Classes of GPU-accelerated mathematical utilities for SCFT calculations.
Classes
class Basis
Symmetry-adapted basis for pseudo-spectral scft.
class BlockDescriptor
A linear homopolymer block within a block copolymer.
class BlockTmpl
Class template for a block in a block copolymer.
class BondDescriptor
A linear bond (including block-bond and joint-bond) within a block copolymer.
class ChiInteraction
Flory-Huggins excess free energy model.
class DPolymerTmpl
class Field
Base class template for a field defined on a spatial grid.
class Interaction
Base class for excess free energy models.
class IntVec
An IntVec<D, T> is a D-component vector of elements of integer type T.
class LuSolver
Solve Ax=b by LU decomposition of A.
class Mesh
Description of a regular grid of points in a periodic domain.
class MeshIterator
Base class for mesh iterator class template.
class MixtureTmpl
A mixture of polymer and solvent species.
class Monomer
Descriptor for a monomer or particle type.
class PolymerTmpl
Descriptor and MDE solver for an acyclic block polymer.
class PropagatorTmpl
Template for propagator classes.
class RealVec
A RealVec<D, T> is D-component vector with elements of floating type T.
class SolventTmpl
Template for a class representing a solvent species.
class SpaceGroup
Crystallographic space group.
class SpaceSymmetry
A SpaceSymmetry represents a crystallographic space group symmetry.
class Species
Base class for a molecular species (polymer or solvent).
class SymmetryGroup
Class template for a group of elements.
class TridiagonalSolver
Solver for Ax=b with tridiagonal matrix A.
struct TWave
Simple wave struct for use within Basis construction.
struct TWaveBzComp
Comparator for TWave objects, based on TWave::indicesBz.
struct TWaveDftComp
Comparator for TWave objects, based on TWave::indicesDft.
struct TWaveNormComp
Comparator for TWave objects, based on TWave::sqNorm.
class UnitCell
Base template for UnitCell<D> classes, D=1, 2 or 3.
class UnitCell< 1 >
1D crystal unit cell.
class UnitCell< 2 >
2D crystal unit cell.
class UnitCell< 3 >
3D crystal unit cell.
class UnitCellBase
Base class template for a crystallographic unit cell.
class Vec
A Vec<D, T><D,T> is a D-component vector with elements of type T.
class Vertex
A junction or chain end in a block polymer.
Functions
std::istream & operator>> (std::istream &in, BlockDescriptor &block)
istream extractor for a BlockDescriptor.
std::ostream & operator<< (std::ostream &out, const BlockDescriptor &block)
ostream inserter for a BlockDescriptor.
std::istream & operator>> (std::istream &in, BondDescriptor &bond)
istream extractor for a BlockDescriptor.
std::istream & operator<< (std::istream &out, const BondDescriptor &bond)
ostream inserter for a BlockDescriptor.
std::istream & operator>> (std::istream &in, Monomer &monomer)
istream extractor for a Monomer.
std::ostream & operator<< (std::ostream &out, const Monomer &monomer)
ostream inserter for a Monomer.
std::istream & operator>> (std::istream &in, Species::Ensemble &policy)
istream extractor for a Species::Ensemble.
std::ostream & operator<< (std::ostream &out, Species::Ensemble policy)
ostream inserter for an Species::Ensemble.
template<class Archive >
void serialize (Archive &ar, Species::Ensemble &policy, const unsigned int version)
Serialize a Species::Ensemble.
std::string makeGroupFileName (int D, std::string groupName)
Generates the file name from a group name.
template<int D>
IntVec< D > shiftToMinimum (IntVec< D > &v, IntVec< D > d, UnitCell< D > const &cell)
Returns minimum magnitude image of DFT wavevector.
template<int D>
std::ostream & operator<< (std::ostream &out, const SpaceGroup< D > &g)
Output stream inserter operator for a SpaceGroup<D>.
template<int D>
std::istream & operator>> (std::istream &in, SpaceGroup< D > &g)
Input stream extractor operator for a SpaceGroup<D>.
template<int D>
bool operator== (const SpaceSymmetry< D > &A, const SpaceSymmetry< D > &B)
Are two SpaceSymmetry objects equivalent?
template<int D>
bool operator!= (const SpaceSymmetry< D > &A, const SpaceSymmetry< D > &B)
Are two SpaceSymmetry objects not equivalent?
template<int D>
SpaceSymmetry< D > operator* (const SpaceSymmetry< D > &A, const SpaceSymmetry< D > &B)
Return the product A*B of two symmetry objects.
template<int D>
IntVec< D > operator* (const SpaceSymmetry< D > &S, const IntVec< D > &V)
Return the IntVec<D> product S*V of a rotation matrix and an IntVec<D>.
template<int D>
IntVec< D > operator* (const IntVec< D > &V, const SpaceSymmetry< D > &S)
Return the IntVec<D> product V*S of an IntVec<D> and a rotation matrix.
template<int D>
std::ostream & operator<< (std::ostream &out, const SpaceSymmetry< D > &A)
Output stream inserter for a SpaceSymmetry<D>
template<int D>
std::istream & operator>> (std::istream &in, SpaceSymmetry< D > &A)
Input stream extractor for a SpaceSymmetry<D>
template<int D>
std::istream & operator>> (std::istream &in, UnitCell< D > &cell)
istream input extractor for a UnitCell<D>.
template<int D>
std::ostream & operator<< (std::ostream &out, UnitCell< D > const &cell)
ostream output inserter for a UnitCell<D>.
template<class Archive , int D>
void serialize (Archive &ar, UnitCell< D > &cell, const unsigned int version)
Serialize to/from an archive.
template<int D>
void readUnitCellHeader (std::istream &in, UnitCell< D > &cell)
Read UnitCell<D> from a field file header (fortran pscf format).
template<int D>
void writeUnitCellHeader (std::ostream &out, UnitCell< D > const &cell)
Write UnitCell<D> to a field file header (fortran pscf format).
std::istream & operator>> (std::istream &in, UnitCell< 1 >::LatticeSystem &lattice)
istream extractor for a 1D UnitCell<1>::LatticeSystem.
std::ostream & operator<< (std::ostream &out, UnitCell< 1 >::LatticeSystem lattice)
ostream inserter for a 1D UnitCell<1>::LatticeSystem.
std::istream & operator>> (std::istream &in, UnitCell< 2 >::LatticeSystem &lattice)
istream extractor for a 2D UnitCell<2>::LatticeSystem.
std::ostream & operator<< (std::ostream &out, UnitCell< 2 >::LatticeSystem lattice)
ostream inserter for a 2D UnitCell<2>::LatticeSystem.
std::istream & operator>> (std::istream &in, UnitCell< 3 >::LatticeSystem &lattice)
istream extractor for a 3D UnitCell<3>::LatticeSystem.
std::ostream & operator<< (std::ostream &out, UnitCell< 3 >::LatticeSystem lattice)
ostream inserter for an 3D UnitCell<3>::LatticeSystem.
template<int D, typename T >
std::istream & operator>> (std::istream &in, IntVec< D, T > &vector)
istream extractor for a IntVec<D, T>.
template<int D, typename T >
std::ostream & operator<< (std::ostream &out, const IntVec< D, T > &vector)
ostream inserter for a IntVec<D, T>.
template<int D, typename T >
bool operator== (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Equality of two IntVec<D> objects.
template<int D, typename T >
bool operator== (const IntVec< D, T > &v1, const Vec< D, T > &v2)
Equality of an IntVec<D> and a Vec<D, T>
template<int D, typename T >
bool operator== (const Vec< D, T > &v1, const IntVec< D, T > &v2)
Equality of an Vec<D, T> and an IntVec<D, T>
template<int D, typename T >
bool operator!= (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Inequality of two IntVec<D, T> objects.
template<int D, typename T >
bool operator!= (const IntVec< D, T > &v1, const Vec< D, T > &v2)
Inequality of an IntVec<D> and a Vec<D, T>
template<int D, typename T >
bool operator!= (const Vec< D, T > &v1, const IntVec< D, T > &v2)
Inequality of a Vec<D, T> and an IntVec<D, T>
template<int D, typename T >
bool operator< (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Less than comparison for two IntVec<D, T>s.
template<int D, typename T >
bool operator<= (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Less than or equal to comparison for two IntVec<D, T>s.
template<int D, typename T >
bool operator> (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Greater than comparison for two IntVec<D, T>s.
template<int D, typename T >
bool operator>= (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Greater than or equal to comparison for two IntVec<D, T>s.
template<int D, typename T >
std::istream & operator>> (std::istream &in, RealVec< D, T > &vector)
istream extractor for a RealVec<D, T>.
template<int D, typename T >
std::ostream & operator<< (std::ostream &out, const RealVec< D, T > &vector)
ostream inserter for a RealVec<D, T>.
template<int D, typename T >
T dot (Vec< D, T > const &v1, Vec< D, T > const &v2)
Return dot product of two vectors.
template<int D, typename T >
Vec< D, T > operator+ (Vec< D, T > const &v1, Vec< D, T > const &v2)
Return the sum of two vectors.
template<int D>
std::istream & operator>> (std::istream &in, Mesh< D > &mesh)
Input stream extractor for reading a Mesh<D> object.
template<int D>
std::ostream & operator<< (std::ostream &out, Mesh< D > &mesh)
Output stream inserter for writing a Mesh<D>::LatticeSystem.
Detailed Description
Classes for polymer self-consistent field theory.
Function Documentation
operator>>() [1/7]
std::istream & Pscf::operator>> (std::istream & in, BlockDescriptor & block)
istream extractor for a BlockDescriptor.
Parameters
in input stream
block BlockDescriptor to be read from stream
Returns
modified input stream
Definition at line 53 of file BlockDescriptor.cpp.
operator<<() [1/8]
std::ostream & Pscf::operator<< (std::ostream & out, const BlockDescriptor & block)
ostream inserter for a BlockDescriptor.
Parameters
out output stream
block BlockDescriptor to be written to stream
Returns
modified output stream
Definition at line 66 of file BlockDescriptor.cpp.
operator>>() [2/7]
std::istream & Pscf::operator>> (std::istream & in, BondDescriptor & bond)
istream extractor for a BlockDescriptor.
Parameters
in input stream
bond BondDescriptor to be read from stream
Returns
modified input stream
Definition at line 41 of file BondDescriptor.cpp.
operator<<() [2/8]
std::istream& Pscf::operator<< (std::istream & out, const BondDescriptor & bond)
ostream inserter for a BlockDescriptor.
Parameters
out output stream
bond BondDescriptor to be written to stream
Returns
modified output stream
operator>>() [3/7]
std::istream & Pscf::operator>> (std::istream & in, Monomer & monomer)
istream extractor for a Monomer.
Parameters
in input stream
monomer Monomer to be read from stream
Returns
modified input stream
Definition at line 27 of file Monomer.cpp.
operator<<() [3/8]
std::ostream & Pscf::operator<< (std::ostream & out, const Monomer & monomer)
ostream inserter for a Monomer.
Parameters
out output stream
monomer Monomer to be written to stream
Returns
modified output stream
Definition at line 38 of file Monomer.cpp.
operator>>() [4/7]
std::istream & Pscf::operator>> (std::istream & in, Species::Ensemble & policy)
istream extractor for a Species::Ensemble.
Parameters
in input stream
policy Species::Ensemble to be read
Returns
modified input stream
Definition at line 22 of file Species.cpp.
References UTIL_THROW.
operator<<() [4/8]
std::ostream & Pscf::operator<< (std::ostream & out, Species::Ensemble policy)
ostream inserter for an Species::Ensemble.
Parameters
out output stream
policy Species::Ensemble to be written
Returns
modified output stream
Definition at line 40 of file Species.cpp.
References UTIL_THROW.
serialize()
template<class Archive >
void Pscf::serialize (Archive & ar, Species::Ensemble & policy, const unsigned int version)
Serialize a Species::Ensemble.
Parameters
ar archive object
policy object to be serialized
version archive version id
Definition at line 127 of file Species.h.
References Util::serializeEnum().
shiftToMinimum()
template<int D>
IntVec<D> Pscf::shiftToMinimum (IntVec< D > & v, IntVec< D > d, UnitCell< D > const & cell)
Returns minimum magnitude image of DFT wavevector.
Parameters
v IntVec<D> containing integer indices of wavevector.
d dimensions of the discrete Fourier transform grid.
cell UnitCell
operator<<() [5/8]
std::ostream & Pscf::operator<< (std::ostream & out, UnitCell< 2 >::LatticeSystem lattice)
ostream inserter for a 2D UnitCell<2>::LatticeSystem.
Parameters
out output stream
lattice UnitCell<2>::LatticeSystem to be written
Returns
modified output stream
Definition at line 186 of file UnitCell2.cpp.
References UTIL_THROW.
operator>>() [5/7]
template<int D, typename T >
std::istream& Pscf::operator>> (std::istream & in, IntVec< D, T > & vector)
istream extractor for a IntVec<D, T>.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector IntVec<D, T> to be read from stream
Returns
modified input stream
Definition at line 85 of file IntVec.h.
operator<<() [6/8]
template<int D, typename T >
std::ostream& Pscf::operator<< (std::ostream & out, const IntVec< D, T > & vector)
ostream inserter for a IntVec<D, T>.
Output a IntVec<D, T> to an ostream, without line breaks.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector IntVec<D, T> to be written to stream
Returns
modified output stream
Definition at line 104 of file IntVec.h.
operator==() [1/3]
template<int D, typename T >
bool Pscf::operator== (const IntVec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Equality of two IntVec<D> objects.
Returns
true if v1 == v2, false otherwise.
Definition at line 120 of file IntVec.h.
operator==() [2/3]
template<int D, typename T >
bool Pscf::operator== (const IntVec< D, T > & v1, const Vec< D, T > & v2) [inline]
Equality of an IntVec<D> and a Vec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 137 of file IntVec.h.
operator==() [3/3]
template<int D, typename T >
bool Pscf::operator== (const Vec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Equality of an Vec<D, T> and an IntVec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 154 of file IntVec.h.
operator!=() [1/3]
template<int D, typename T >
bool Pscf::operator!= (const IntVec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Inequality of two IntVec<D, T> objects.
Returns
true if v1 != v2, false if v1 == v2.
Definition at line 164 of file IntVec.h.
operator!=() [2/3]
template<int D, typename T >
bool Pscf::operator!= (const IntVec< D, T > & v1, const Vec< D, T > & v2) [inline]
Inequality of an IntVec<D> and a Vec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 174 of file IntVec.h.
operator!=() [3/3]
template<int D, typename T >
bool Pscf::operator!= (const Vec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Inequality of a Vec<D, T> and an IntVec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 184 of file IntVec.h.
operator<()
template<int D, typename T >
bool Pscf::operator< (const IntVec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Less than comparison for two IntVec<D, T>s.
Elements with lower array indices are treated as more signficant.
Returns
true if v1 < v2, false otherwise.
Definition at line 196 of file IntVec.h.
operator<=()
template<int D, typename T >
bool Pscf::operator<= (const IntVec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Less than or equal to comparison for two IntVec<D, T>s.
Elements with lower array indices are more signficant digits.
Returns
true if v1 < v2, false otherwise.
Definition at line 220 of file IntVec.h.
operator>()
template<int D, typename T >
bool Pscf::operator> (const IntVec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Greater than comparison for two IntVec<D, T>s.
Returns
true if v1 > v2, false otherwise.
Definition at line 242 of file IntVec.h.
operator>=()
template<int D, typename T >
bool Pscf::operator>= (const IntVec< D, T > & v1, const IntVec< D, T > & v2) [inline]
Greater than or equal to comparison for two IntVec<D, T>s.
Returns
true if v1 >= v2, false otherwise.
Definition at line 252 of file IntVec.h.
operator>>() [6/7]
template<int D, typename T >
std::istream& Pscf::operator>> (std::istream & in, RealVec< D, T > & vector)
istream extractor for a RealVec<D, T>.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector RealVec<D, T> to be read from stream
Returns
modified input stream
Definition at line 89 of file RealVec.h.
operator<<() [7/8]
template<int D, typename T >
std::ostream& Pscf::operator<< (std::ostream & out, const RealVec< D, T > & vector)
ostream inserter for a RealVec<D, T>.
Output a RealVec<D, T> to an ostream, without line breaks.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector RealVec<D, T> to be written to stream
Returns
modified output stream
Definition at line 108 of file RealVec.h.
dot()
template<int D, typename T >
T Pscf::dot (Vec< D, T > const & v1, Vec< D, T > const & v2) [inline]
Return dot product of two vectors.
Parameters
v1 first input vector
v2 second input vector
Returns
dot product v1.v2
Definition at line 283 of file Vec.h.
References dot(), and Util::setToZero().
Referenced by dot().
operator+()
template<int D, typename T >
Vec<D, T> Pscf::operator+ (Vec< D, T > const & v1, Vec< D, T > const & v2) [inline]
Return the sum of two vectors.
Parameters
v1 first input vector
v2 second input vector
Returns
sum v1 + v2
Definition at line 302 of file Vec.h.
References Pscf::Vec< D, T >::add().
operator>>() [7/7]
template<int D>
std::istream & Pscf::operator>> (std::istream & in, Mesh< D > & mesh)
Input stream extractor for reading a Mesh<D> object.
Parameters
in input stream
mesh Mesh<D> object to be read
Returns
modified input stream
Definition at line 136 of file Mesh.tpp.
References Pscf::Mesh< D >::setDimensions(), and UTIL_CHECK.
operator<<() [8/8]
template<int D>
std::ostream & Pscf::operator<< (std::ostream & out, Mesh< D > & mesh)
Output stream inserter for writing a Mesh<D>::LatticeSystem.
Parameters
out output stream
mesh Mesh<D> to be written
Returns
modified output stream
Definition at line 149 of file Mesh.tpp.