Util Namespace Reference
Utility classes for scientific computation.
Classes
class Ar1Process
Generator for a discrete AR(1) Markov process.
class Array
Array container class template.
class ArrayIterator
Forward iterator for an Array or a C array.
class ArraySet
A container for pointers to a subset of elements of an associated array.
class ArrayStack
A stack of fixed capacity.
class AutoCorr
Auto-correlation function for one sequence of Data values.
class AutoCorrArray
Auto-correlation function for an ensemble of sequences.
class AutoCorrelation
Auto-correlation function, using hierarchical algorithm.
class AutoCorrStage
Hierarchical auto-correlation function algorithm.
class Average
Calculates the average and variance of a sampled property.
class AverageStage
Evaluate average with hierarchical blocking error analysis.
class Begin
Beginning line of a composite parameter block.
class BinaryFileIArchive
Saving archive for binary istream.
class BinaryFileOArchive
Saving / output archive for binary ostream.
class Binomial
Class for binomial coefficients (all static members)
class Bit
Represents a specific bit location within an unsigned int.
class Blank
An empty line within a parameter file.
class Bool
Wrapper for an bool value, for formatted ostream output.
class CardinalBSpline
A cardinal B-spline basis function.
class CArray2DParam
A Parameter associated with a 2D built-in C array.
class CArrayParam
A Parameter associated with a 1D C array.
class Constants
Mathematical constants.
class ConstArrayIterator
Forward const iterator for an Array or a C array.
class ConstPArrayIterator
Forward iterator for a PArray.
class DArray
Dynamically allocatable contiguous array template.
class DArrayParam
A Parameter associated with a DArray container.
class Dbl
Wrapper for a double precision number, for formatted ostream output.
class Distribution
A distribution (or histogram) of values for a real variable.
class DMatrix
Dynamically allocated Matrix.
class DMatrixParam
A Parameter associated with a 2D built-in C array.
class DPArray
A dynamic array that only holds pointers to its elements.
class DRaggedMatrix
Dynamically allocated RaggedMatrix.
class DSArray
Dynamically allocated array with variable logical size.
class DSymmMatrixParam
A Parameter associated with a symmetric DMatrix.
class End
End bracket of a ParamComposite parameter block.
class Exception
A user-defined exception.
class Factory
Factory template.
class FArray
A fixed size (static) contiguous array template.
class FArrayParam
A Parameter associated with a FArray container.
class FileMaster
A FileMaster manages input and output files for a simulation.
class FlagSet
A set of boolean variables represented by characters.
class FlexPtr
A pointer that may or may not own the object to which it points.
class FMatrix
Fixed Size Matrix.
class Format
Base class for output wrappers for formatted C++ ostream output.
class FPArray
Statically allocated pointer array.
class FSArray
A fixed capacity (static) contiguous array with a variable logical size.
class GArray
An automatically growable array, analogous to a std::vector.
class GPArray
An automatically growable PArray.
class Grid
A grid of points indexed by integer coordinates.
class GridArray
Multi-dimensional array with the dimensionality of space.
class GStack
An automatically growable Stack.
class IFunctor
Interface for functor that wraps a void function with one argument (abstract).
class IFunctor< void >
Interface for functor that wraps a void function with no arguments (abstract).
class Int
Wrapper for an int, for formatted ostream output.
class IntDistribution
A distribution (or histogram) of values for an int variable.
class IntVector
An IntVector is an integer Cartesian vector.
class Label
A label string in a file format.
class List
Linked list class template.
class ListArray
An array of objects that are accessible by one or more linked List objects.
class ListIterator
Bidirectional iterator for a List.
class Lng
Wrapper for a long int, for formatted ostream output.
class Log
A static class that holds a log output stream.
class Manager
Template container for pointers to objects with a common base class.
class Matrix
Two-dimensional array container template (abstract).
class MeanSqDispArray
Mean-squared displacement (MSD) vs.
class Memory
Provides method to allocate array.
class MemoryCounter
Archive to computed packed size of a sequence of objects, in bytes.
class MemoryIArchive
Input archive for packed heterogeneous binary data.
class MemoryOArchive
Save archive for packed heterogeneous binary data.
class MethodFunctor
Functor that wraps a one-argument class member function.
class MethodFunctor< Object, void >
Functor that wraps a class member function with no arguments.
class MpiFileIo
Identifies whether this processor may do file I/O.
class MpiLoader
Provides methods for MPI-aware loading of data from input archive.
class MpiLogger
Allows information from every processor in a communicator, to be output in rank sequence.
class MpiStructBuilder
A MpiStructBuilder objects is used to create an MPI Struct datatype.
class MpiTraits
Default MpiTraits class.
class MpiTraits< bool >
MpiTraits<bool> explicit specialization.
class MpiTraits< char >
MpiTraits<char> explicit specialization.
class MpiTraits< double >
MpiTraits<double> explicit specialization.
class MpiTraits< float >
MpiTraits<float> explicit specialization.
class MpiTraits< int >
MpiTraits<int> explicit specialization.
class MpiTraits< IntVector >
Explicit specialization MpiTraits<IntVector>.
class MpiTraits< long >
MpiTraits<long> explicit specialization.
class MpiTraits< long double >
MpiTraits<long double> explicit specialization.
class MpiTraits< Rational >
Explicit specialization MpiTraits<Rational>.
class MpiTraits< short >
MpiTraits<short> explicit specialization.
class MpiTraits< Tensor >
Explicit specialization MpiTraits<Tensor>.
class MpiTraits< unsigned char >
MpiTraits<unsigned char> explicit specialization.
class MpiTraits< unsigned int >
MpiTraits<unsigned int> explicit specialization.
class MpiTraits< unsigned long >
MpiTraits<unsigned long> explicit specialization.
class MpiTraits< unsigned short >
MpiTraits<unsigned short> explicit specialization.
class MpiTraits< Vector >
Explicit specialization MpiTraits<Vector>.
class MpiTraitsNoType
Base class for MpiTraits with no type.
class MTRand
Generates double floating point numbers in the half-open interval [0, 1)
class MTRand53
generates 53 bit resolution doubles in the half-open interval [0, 1)
class MTRand_closed
Generates double floating point numbers in the closed interval [0, 1].
class MTRand_int32
Mersenne Twister random number generator engine.
class MTRand_open
Generates double floating point numbers in the open interval (0, 1).
class Node
Linked List Node, class template.
class Notifier
Abstract template for a notifier (or subject) in the Observer design pattern.
class Observer
Abstract class template for observer in the observer design pattern.
class OptionalLabel
An optional Label string in a file format.
class Pair
An array of exactly 2 objects.
class ParamComponent
Abstract base class for classes that input and output parameters to file.
class ParamComposite
An object that can read multiple parameters from file.
class Parameter
A single variable in a parameter file.
class PArray
An array that only holds pointers to its elements.
class PArrayIterator
Forward iterator for a PArray.
class Polynomial
A Polynomial (i.e,.
class RadialDistribution
Distribution (or histogram) of values for particle separations.
class RaggedMatrix
A 2D array in which different rows can have different lengths.
class Random
Random number generator.
class RArray
An Array that acts as a reference to another Array or C array.
class Rational
A Rational number (a ratio of integers).
class RingBuffer
Class for storing history of previous values in an array.
class ScalarParam
Template for a Parameter object associated with a scalar variable.
class ScopedPtr
A very simple RAII pointer.
class Serializable
Abstract class for serializable objects.
class Setable
Template for a value that can be set or declared null (i.e., unknown).
class Signal
Notifier (or subject) in the Observer design pattern.
class Signal< void >
Notifier (or subject) in the Observer design pattern (zero parameters).
class SSet
Statically allocated array of pointers to an unordered set.
class Str
Wrapper for a std::string, for formatted ostream output.
class SymmTensorAverage
Calculates averages of all components of a Tensor-valued variable.
class Tensor
A Tensor represents a Cartesian tensor.
class TensorAverage
Calculates averages of all components of a Tensor-valued variable.
class TextFileIArchive
Loading archive for text istream.
class TextFileOArchive
Saving archive for character based ostream.
class Timer
Wall clock timer.
class Vector
A Vector is a Cartesian vector.
class XdrFileIArchive
Loading / input archive for binary XDR file.
class XdrFileOArchive
Saving / output archive for binary XDR file.
class XmlAttribute
Parser for an XML attribute.
class XmlBase
Base class for classes that parse XML markup tags.
class XmlEndTag
Parser for an XML end tag.
class XmlStartTag
Parser for an XML start tag.
class XmlXmlTag
Parser for an XML file declaration tag (first line in file).
Typedefs
typedef unsigned char Byte
Define a `Byte` type.
Functions
float product (float a, float b)
Product for float Data.
double product (double a, double b)
Product for double Data.
double product (const Vector &a, const Vector &b)
Dot product for Vector Data.
double product (const Tensor &a, const Tensor &b)
Double contraction for Tensor Data.
complex< float > product (complex< float > a, complex< float > b)
Inner product for complex<float> Data.
complex< double > product (complex< double > a, complex< double > b)
Inner product for complex<double> Data.
void setToZero (int &value)
Set an int variable to zero.
void setToZero (float &value)
Set a float variable to zero.
void setToZero (double &value)
Set a double variable to zero.
void setToZero (Vector &value)
Set a Vector variable to zero.
void setToZero (Tensor &value)
Set a Vector variable to zero.
void setToZero (complex< float > &value)
Set a complex<float> variable to zero.
void setToZero (complex< double > &value)
Set a complex<double> variable to zero.
template<typename T >
int memorySize (T &data)
Function template to compute memory size of one object.
template<class Archive , typename T >
void serialize (Archive &ar, T &data, const unsigned int version)
Serialize one object of type T.
template<class Archive , typename T >
void serializeEnum (Archive &ar, T &data, const unsigned int version=0)
Serialize an enumeration value.
template<class Archive , typename T >
void serializeCheck (Archive &ar, T &data, const char *label=``)
Save a value, or save and check correctness on loading.
template<typename Data >
std::istream & operator>> (std::istream &in, Pair< Data > &pair)
Input a Pair from an istream.
template<typename Data >
std::ostream & operator<< (std::ostream &out, const Pair< Data > &pair)
Output a Pair to an ostream, without line breaks.
std::istream & operator>> (std::istream &in, Bool &object)
Input stream extractor for an Bool object.
std::ostream & operator<< (std::ostream &out, const Bool &object)
Output stream inserter for an Bool object.
std::istream & operator>> (std::istream &in, Dbl &object)
Input stream extractor for an Dbl object.
std::ostream & operator<< (std::ostream &out, const Dbl &object)
Output stream inserter for an Dbl object.
std::istream & operator>> (std::istream &in, Int &object)
Input stream extractor for an Int object.
std::ostream & operator<< (std::ostream &out, const Int &object)
Output stream inserter for an Int object.
std::istream & operator>> (std::istream &in, Lng &object)
Input stream extractor for an Lng object.
std::ostream & operator<< (std::ostream &out, const Lng &object)
Output stream inserter for an Lng object.
std::istream & operator>> (std::istream &in, Str &object)
Input stream extractor for an Str object.
std::ostream & operator<< (std::ostream &out, const Str &object)
Output stream inserter for an Str object.
template<> void write (std::ostream &out, double data)
Explicit specialization of write for double data.
template<> void write (std::ostream &out, std::complex< double > data)
Explicit specialization of write for double data.
template<> void write (std::ostream &out, int data)
Explicit specialization of write for int data.
template<> void write (std::ostream &out, long data)
Explicit specialization of write for long data.
template<> void write (std::ostream &out, bool data)
Explicit specialization of write for bool data.
template<typename Type >
void write (std::ostream &out, Type data)
Function template for output in a standard format.
template<> void write (std::ostream &out, std::string data)
Explicit specialization of write for std::string data.
bool feq (double x, double y, double eps=1.0E-10)
Are two floating point numbers equal to within round-off error?
int gcd (int a, int b)
Compute greatest common divisor (gcd) of two integers.
template<typename T >
bool operator== (Polynomial< T > &a, Polynomial< T > &b)
Equality operator for polynomials.
template<typename T >
bool operator!= (Polynomial< T > &a, Polynomial< T > &b)
Inequality operator for polynomials.
template<typename T >
Polynomial< T > operator- (Polynomial< T > const &a)
Unary negation of polynomial.
std::ostream & operator<< (std::ostream &out, Rational const &rational)
Output stream inserter for a Rational.
Rational operator+ (Rational const &a, Rational const &b)
Compute sum of two rationals.
Rational operator+ (Rational const &a, int b)
Compute sum of rational and integer.
Rational operator+ (int b, Rational const &a)
Compute sum of integer and integer.
Rational operator- (Rational const &a, Rational const &b)
Compute difference of rationals.
Rational operator- (Rational const &a, int b)
Compute difference of rational and integer.
Rational operator- (int b, Rational const &a)
Compute difference of integer and rational.
Rational operator* (Rational const &a, Rational const &b)
Compute product of rationals.
Rational operator* (Rational const &a, int b)
Compute product of rational and integer.
Rational operator* (int b, Rational const &a)
Compute product of integer and rational.
Rational operator/ (Rational const &a, Rational const &b)
Compute quotient of two rationals.
Rational operator/ (Rational const &a, int b)
Compute quotient Rational divided by integer.
Rational operator/ (int b, Rational const &a)
Compute quotient integer divided by Rational.
Rational operator- (Rational const &a)
Unary negation of Rational.
bool operator== (Rational const &a, Rational const &b)
Equality operators.
bool operator== (Rational const &a, int b)
Equality operator for a Rational and an integer.
bool operator== (int b, Rational const &a)
Equality operator for an integer and a Rational.
bool operator!= (Rational const &a, Rational const &b)
Inequality operators.
bool operator!= (Rational const &a, int b)
Inequality operator for a Rational and an integer.
bool operator!= (int b, Rational const &a)
Inequality operator for an integer and a Rational.
void MpiThrow (Exception &e)
Function to throw exception in MPI code.
void initStatic ()
Guarantee initialization of all static class members in Util namespace.
int rStrip (std::string &string)
Strip trailing whitespace from a string.
void checkString (std::istream &in, const std::string &expected)
Extract string from stream, and compare to expected value.
std::string toString (int n)
Return string representation of an integer.
bool getLine (std::istream &in, std::stringstream &line)
Read the next line into a stringstream.
bool getNextLine (std::istream &in, std::string &line)
Read the next non-empty line into a string, strip trailing whitespace.
bool getNextLine (std::istream &in, std::stringstream &line)
Read next non-empty line into a stringstream, strip trailing whitespace.
void checkRequiredIstream (std::istream &in)
Check status of a std::istream just before reading required variable.
template<typename D , typename B , typename M >
ptrdiff_t memberOffset (D &object, M B::*memPtr)
Template for calculating offsets of data members.
template<typename D , typename B >
ptrdiff_t baseOffset (D &object)
Template for calculating offsets of base class subobjects.
template<> void send< bool > (MPI::Comm &comm, bool &data, int dest, int tag)
Explicit specialization of send for bool data.
template<> void recv< bool > (MPI::Comm &comm, bool &data, int source, int tag)
Explicit specialization of recv for bool data.
template<> void bcast< bool > (MPI::Intracomm &comm, bool &data, int root)
Explicit specialization of bcast for bool data.
template<> void send< std::string > (MPI::Comm &comm, std::string &data, int dest, int tag)
Explicit specialization of send for std::string data.
template<> void recv< std::string > (MPI::Comm &comm, std::string &data, int source, int tag)
Explicit specialization of recv for std::string data.
template<> void bcast< std::string > (MPI::Intracomm &comm, std::string &data, int root)
Explicit specialization of bcast for std::string data.
template<typename T >
void send (MPI::Comm &comm, T &data, int dest, int tag)
Send a single T value.
template<typename T >
void recv (MPI::Comm &comm, T &data, int source, int tag)
Receive a single T value.
template<typename T >
void bcast (MPI::Intracomm &comm, T &data, int root)
Broadcast a single T value.
template<typename T >
void send (MPI::Comm &comm, T *array, int count, int dest, int tag)
Send a C-array of T values.
template<typename T >
void recv (MPI::Comm &comm, T *array, int count, int source, int tag)
Receive a C-array of T objects.
template<typename T >
void bcast (MPI::Intracomm &comm, T *array, int count, int root)
Broadcast a C-array of T objects.
template<typename T >
void send (MPI::Comm &comm, DArray< T > &array, int count, int dest, int tag)
Send a DArray<T> container.
template<typename T >
void recv (MPI::Comm &comm, DArray< T > &array, int count, int source, int tag)
Receive a DArray<T> container.
template<typename T >
void bcast (MPI::Intracomm &comm, DArray< T > &array, int count, int root)
Broadcast a DArray<T> container.
template<typename T >
void send (MPI::Comm &comm, DMatrix< T > &matrix, int m, int n, int dest, int tag)
Send a DMatrix<T> container.
template<typename T >
void recv (MPI::Comm &comm, DMatrix< T > &matrix, int m, int n, int source, int tag)
Receive a DMatrix<T> container.
template<typename T >
void bcast (MPI::Intracomm &comm, DMatrix< T > &matrix, int m, int n, int root)
Broadcast a DMatrix<T> container.
std::istream & operator>> (std::istream &in, Label label)
Extractor for Label.
std::ostream & operator<< (std::ostream &out, Label label)
Inserter for Label.
template<typename T >
bool isNull (FlexPtr< T > p)
Return true iff the enclosed built-in pointer is null.
template<typename T >
bool isNull (T *ptr)
Return true iff a built-in pointer is null.
template<typename T >
bool isNull (ScopedPtr< T > p)
Return true iff the enclosed built-in pointer is null.
bool operator== (const IntVector &v1, const IntVector &v2)
Equality for IntVectors.
bool operator== (const IntVector &v1, const int *v2)
Equality of IntVector and C array.
bool operator== (const int *v1, const IntVector &v2)
Equality of C array and IntVector.
bool operator!= (const IntVector &v1, const IntVector &v2)
Inequality of two IntVectors.
bool operator!= (const IntVector &v1, const int *v2)
Inequality of IntVector and C array.
bool operator!= (const int *v1, const IntVector &v2)
Inequality of C array and IntVector.
std::istream & operator>> (std::istream &in, IntVector &vector)
istream extractor for a IntVector.
std::ostream & operator<< (std::ostream &out, const IntVector &vector)
ostream inserter for a IntVector.
bool operator== (const Tensor &t1, const Tensor &t2)
Equality for Tensors.
bool operator== (const Tensor &t1, const double t2[][Dimension])
Equality of Tensor and 2D C array.
bool operator== (const double t1[][Dimension], const Tensor &t2)
Equality of C array and Tensor.
bool operator!= (const Tensor &t1, const Tensor &t2)
Negation of t1 == t2 (tensors t1 and t2)
bool operator!= (const Tensor &t1, const double a2[][Dimension])
Negation of t1 == a2 (tensor t1, 2D array a2)
bool operator!= (const double a1[][Dimension], const Tensor &t2)
Negation of t1 == a2 (tensor t2, 2D array a1)
std::istream & operator>> (std::istream &in, Tensor &tensor)
istream extractor for a Tensor.
std::ostream & operator<< (std::ostream &out, const Tensor &tensor)
ostream inserter for a Tensor.
bool operator== (const Vector &v1, const Vector &v2)
Equality for Vectors.
bool operator== (const Vector &v1, const double *v2)
Equality of Vector and C array.
bool operator== (const double *v1, const Vector &v2)
Equality of C array and Vector.
bool operator!= (const Vector &v1, const Vector &v2)
Inequality of two Vectors.
bool operator!= (const Vector &v1, const double *v2)
Inequality of Vector and C array.
bool operator!= (const double *v1, const Vector &v2)
Inequality of C array and Vector.
std::istream & operator>> (std::istream &in, Vector &vector)
istream extractor for a Vector.
std::ostream & operator<< (std::ostream &out, const Vector &vector)
ostream inserter for a Vector.
Variables
const int Dimension = 3
Dimensionality of space.
const int DimensionSq = Dimension*Dimension
Square of Dimensionality of space.
Detailed Description
Utility classes for scientific computation.
Typedef Documentation
Byte
typedef unsigned char Util::Byte
Define a `Byte` type.
Definition at line 19 of file Byte.h.
Function Documentation
product() [1/6]
float Util::product (float a, float b) [inline]
Product for float Data.
Definition at line 22 of file product.h.
Referenced by Util::AutoCorr< Data, Product >::autoCorrelation(), Util::AutoCorr< Data, Product >::corrTime(), Util::AutoCorrArray< Data, Product >::corrTime(), Util::AutoCorr< Data, Product >::output(), Util::AutoCorrStage< Data, Product >::sample(), Util::AutoCorr< Data, Product >::sample(), and Util::AutoCorrArray< Data, Product >::sample().
product() [2/6]
double Util::product (double a, double b) [inline]
Product for double Data.
Definition at line 28 of file product.h.
product() [3/6]
double Util::product (const Vector & a, const Vector & b) [inline]
Dot product for Vector Data.
Definition at line 34 of file product.h.
References Util::Vector::dot().
product() [4/6]
double Util::product (const Tensor & a, const Tensor & b) [inline]
Double contraction for Tensor Data.
Definition at line 40 of file product.h.
References Dimension.
product() [5/6]
complex<float> Util::product (complex< float > a, complex< float > b) [inline]
Inner product for complex<float> Data.
Definition at line 55 of file product.h.
product() [6/6]
complex<double> Util::product (complex< double > a, complex< double > b) [inline]
Inner product for complex<double> Data.
Definition at line 61 of file product.h.
setToZero() [1/7]
void Util::setToZero (int & value) [inline]
Set an int variable to zero.
Parameters
value value to be zeroed.
Definition at line 25 of file setToZero.h.
Referenced by Util::AutoCorr< Data, Product >::AutoCorr(), Util::AutoCorrArray< Data, Product >::AutoCorrArray(), Util::AutoCorrStage< Data, Product >::autoCorrelation(), Util::AutoCorrStage< Data, Product >::AutoCorrStage(), Util::AutoCorr< Data, Product >::clear(), Util::AutoCorrStage< Data, Product >::clear(), Util::MeanSqDispArray< Data >::clear(), Util::AutoCorrArray< Data, Product >::clear(), Util::AutoCorr< Data, Product >::corrTime(), Util::AutoCorrArray< Data, Product >::corrTime(), Util::AutoCorrStage< Data, Product >::corrTime(), Pscf::dot(), Util::Polynomial< double >::operator*=(), Util::Polynomial< double >::operator=(), Util::AutoCorrStage< Data, Product >::output(), Util::AutoCorrStage< Data, Product >::sample(), and Pscf::Vec< D, int >::setToZero().
setToZero() [2/7]
void Util::setToZero (float & value) [inline]
Set a float variable to zero.
Parameters
value value to be zeroed.
Definition at line 33 of file setToZero.h.
setToZero() [3/7]
void Util::setToZero (double & value) [inline]
Set a double variable to zero.
Parameters
value value to be zeroed.
Definition at line 41 of file setToZero.h.
setToZero() [4/7]
void Util::setToZero (Vector & value) [inline]
Set a Vector variable to zero.
Parameters
value value to be zeroed.
Definition at line 49 of file setToZero.h.
References Util::Vector::zero().
setToZero() [5/7]
void Util::setToZero (Tensor & value) [inline]
Set a Vector variable to zero.
Parameters
value value to be zeroed.
Definition at line 57 of file setToZero.h.
References Util::Tensor::zero().
setToZero() [6/7]
void Util::setToZero (complex< float > & value) [inline]
Set a complex<float> variable to zero.
Parameters
value value to be zeroed.
Definition at line 65 of file setToZero.h.
setToZero() [7/7]
void Util::setToZero (complex< double > & value) [inline]
Set a complex<double> variable to zero.
Parameters
value value to be zeroed.
Definition at line 73 of file setToZero.h.
memorySize()
template<typename T >
int Util::memorySize (T & data)
Function template to compute memory size of one object.
Definition at line 130 of file MemoryCounter.h.
References Util::MemoryCounter::size().
operator>>() [1/10]
template<typename Data >
std::istream& Util::operator>> (std::istream & in, Pair< Data > & pair)
Input a Pair from an istream.
Parameters
in istream from which to read
pair Pair to be read
Definition at line 44 of file Pair.h.
operator<<() [1/11]
template<typename Data >
std::ostream& Util::operator<< (std::ostream & out, const Pair< Data > & pair)
Output a Pair to an ostream, without line breaks.
Parameters
out ostream to which to write
pair Pair to be written
Definition at line 57 of file Pair.h.
operator>>() [2/10]
std::istream & Util::operator>> (std::istream & in, Bool & object)
Input stream extractor for an Bool object.
Parameters
in input stream
object Bool object to be read from stream
Returns
modified input stream
Definition at line 47 of file Bool.cpp.
operator<<() [2/11]
std::ostream & Util::operator<< (std::ostream & out, const Bool & object)
Output stream inserter for an Bool object.
Parameters
out output stream
object Bool to be written to stream
Returns
modified output stream
Definition at line 56 of file Bool.cpp.
operator>>() [3/10]
std::istream & Util::operator>> (std::istream & in, Dbl & object)
Input stream extractor for an Dbl object.
Parameters
in input stream
object Dbl object to be read from stream
Returns
modified input stream
Definition at line 73 of file Dbl.cpp.
operator<<() [3/11]
std::ostream & Util::operator<< (std::ostream & out, const Dbl & object)
Output stream inserter for an Dbl object.
Parameters
out output stream
object Dbl to be written to stream
Returns
modified output stream
Definition at line 86 of file Dbl.cpp.
operator>>() [4/10]
std::istream & Util::operator>> (std::istream & in, Int & object)
Input stream extractor for an Int object.
Parameters
in input stream
object Int object to be read from stream
Returns
modified input stream
Definition at line 71 of file Int.cpp.
operator<<() [4/11]
std::ostream & Util::operator<< (std::ostream & out, const Int & object)
Output stream inserter for an Int object.
Parameters
out output stream
object Int to be written to stream
Returns
modified output stream
Definition at line 84 of file Int.cpp.
operator>>() [5/10]
std::istream & Util::operator>> (std::istream & in, Lng & object)
Input stream extractor for an Lng object.
Parameters
in input stream
object Lng object to be read from stream
Returns
modified input stream
Definition at line 53 of file Lng.cpp.
operator<<() [5/11]
std::ostream & Util::operator<< (std::ostream & out, const Lng & object)
Output stream inserter for an Lng object.
Parameters
out output stream
object Lng to be written to stream
Returns
modified output stream
Definition at line 66 of file Lng.cpp.
operator>>() [6/10]
std::istream & Util::operator>> (std::istream & in, Str & object)
Input stream extractor for an Str object.
Parameters
in input stream
object Str object to be read from stream
Returns
modified input stream
Definition at line 49 of file Str.cpp.
operator<<() [6/11]
std::ostream & Util::operator<< (std::ostream & out, const Str & object)
Output stream inserter for an Str object.
Parameters
out output stream
object Str to be written to stream
Returns
modified output stream
Definition at line 58 of file Str.cpp.
write() [1/6]
template<>
void Util::write (std::ostream & out, double data)
Explicit specialization of write for double data.
Definition at line 20 of file write.cpp.
write() [2/6]
template<>
void Util::write (std::ostream & out, std::complex< double > data)
Explicit specialization of write for double data.
Definition at line 24 of file write.cpp.
write() [3/6]
template<>
void Util::write (std::ostream & out, int data)
Explicit specialization of write for int data.
Definition at line 28 of file write.cpp.
write() [4/6]
template<>
void Util::write (std::ostream & out, long data)
Explicit specialization of write for long data.
Definition at line 32 of file write.cpp.
write() [5/6]
template<>
void Util::write (std::ostream & out, bool data)
Explicit specialization of write for bool data.
Definition at line 36 of file write.cpp.
write() [6/6]
template<>
void Util::write (std::ostream & out, std::string data)
Explicit specialization of write for std::string data.
operator==() [1/13]
template<typename T >
bool Util::operator== (Polynomial< T > & a, Polynomial< T > & b)
Equality operator for polynomials.
Two polynomials are equal iff they have the same degree and the the same values for all coefficients.
Parameters
a 1st polynomial
b 2nd polynomial
Returns
true if a != b
Definition at line 676 of file Polynomial.h.
operator!=() [1/13]
template<typename T >
bool Util::operator!= (Polynomial< T > & a, Polynomial< T > & b)
Inequality operator for polynomials.
Parameters
a 1st polynomial
b 2nd polynomial
Returns
true if a != b
Definition at line 695 of file Polynomial.h.
operator-() [1/5]
template<typename T >
Polynomial<T> Util::operator- (Polynomial< T > const & a) [inline]
Unary negation of polynomial.
Parameters
a input polynomial
Returns
negated polynomial -a
Definition at line 706 of file Polynomial.h.
operator<<() [7/11]
std::ostream & Util::operator<< (std::ostream & out, Rational const & rational)
Output stream inserter for a Rational.
Output elements of a rational to stream, without line breaks.
Parameters
out output stream
rational Rational to be written to stream
Returns
modified output stream
Definition at line 16 of file Rational.cpp.
References UTIL_CHECK.
operator+() [1/3]
Rational Util::operator+ (Rational const & a, Rational const & b) [inline]
Compute sum of two rationals.
Parameters
a 1st argument
b 2st argument
Returns
sum a + b
Definition at line 490 of file Rational.h.
operator+() [2/3]
Rational Util::operator+ (Rational const & a, int b) [inline]
Compute sum of rational and integer.
Parameters
a Rational argument
b integer argument
Returns
sum a + b
Definition at line 505 of file Rational.h.
operator+() [3/3]
Rational Util::operator+ (int b, Rational const & a) [inline]
Compute sum of integer and integer.
Parameters
b integer argument
a Rational argument
Returns
sum a + b
Definition at line 519 of file Rational.h.
operator-() [2/5]
Rational Util::operator- (Rational const & a, Rational const & b) [inline]
Compute difference of rationals.
Parameters
a 1st argument
b 2st argument
Returns
difference a - b
Definition at line 530 of file Rational.h.
operator-() [3/5]
Rational Util::operator- (Rational const & a, int b) [inline]
Compute difference of rational and integer.
Parameters
a Rational argument
b integer argument
Returns
difference a - b
Definition at line 545 of file Rational.h.
operator-() [4/5]
Rational Util::operator- (int b, Rational const & a) [inline]
Compute difference of integer and rational.
Parameters
b integer argument
a Rational argument
Returns
difference b - a
Definition at line 559 of file Rational.h.
operator*() [1/3]
Rational Util::operator* (Rational const & a, Rational const & b) [inline]
Compute product of rationals.
Parameters
a 1st Rational argument
b 2st Rational argument
Returns
product a*b
Definition at line 573 of file Rational.h.
operator*() [2/3]
Rational Util::operator* (Rational const & a, int b) [inline]
Compute product of rational and integer.
Parameters
a Rational argument
b integer argument
Returns
product a*b
Definition at line 588 of file Rational.h.
operator*() [3/3]
Rational Util::operator* (int b, Rational const & a) [inline]
Compute product of integer and rational.
Parameters
b integer argument
a Rational argument
Returns
product a*b
Definition at line 599 of file Rational.h.
operator/() [1/3]
Rational Util::operator/ (Rational const & a, Rational const & b) [inline]
Compute quotient of two rationals.
Parameters
a 1st Rational argument (numerator)
b 2st Rational argument (denominator)
Returns
ratio a/b
Definition at line 610 of file Rational.h.
References UTIL_THROW.
operator/() [2/3]
Rational Util::operator/ (Rational const & a, int b) [inline]
Compute quotient Rational divided by integer.
Parameters
a Rational argument (numerator)
b integer argument (denominator)
Returns
ratio a/b
Definition at line 628 of file Rational.h.
References UTIL_THROW.
operator/() [3/3]
Rational Util::operator/ (int b, Rational const & a) [inline]
Compute quotient integer divided by Rational.
Parameters
b integer argument (numerator)
a Rational argument (denominator)
Returns
ratio b/a
Definition at line 644 of file Rational.h.
References UTIL_THROW.
operator-() [5/5]
Rational Util::operator- (Rational const & a) [inline]
Unary negation of Rational.
Parameters
a Rational number
Returns
negation -a
Definition at line 661 of file Rational.h.
operator==() [2/13]
bool Util::operator== (Rational const & a, Rational const & b) [inline]
Equality operators.
Equality operator for two Rational numbers.
Parameters
a 1st Rational
b 2nd Rational
Returns
true if equal, false otherwise
Definition at line 674 of file Rational.h.
operator==() [3/13]
bool Util::operator== (Rational const & a, int b) [inline]
Equality operator for a Rational and an integer.
Parameters
a Rational number
b integer number
Returns
true if equal, false otherwise
Definition at line 684 of file Rational.h.
operator==() [4/13]
bool Util::operator== (int b, Rational const & a) [inline]
Equality operator for an integer and a Rational.
Parameters
b integer number
a Rational number
Returns
true if equal, false otherwise
Definition at line 694 of file Rational.h.
operator!=() [2/13]
bool Util::operator!= (Rational const & a, Rational const & b) [inline]
Inequality operators.
Inequality operator for two Rational numbers.
Parameters
a 1st Rational
b 2nd Rational
Returns
true if unequal, false if equal
Definition at line 706 of file Rational.h.
operator!=() [3/13]
bool Util::operator!= (Rational const & a, int b) [inline]
Inequality operator for a Rational and an integer.
Parameters
a Rational number
b integer number
Returns
true if unequal, false if equal
Definition at line 716 of file Rational.h.
operator!=() [4/13]
bool Util::operator!= (int b, Rational const & a) [inline]
Inequality operator for an integer and a Rational.
Parameters
b integer number
a Rational number
Returns
true if unequal, false if equal
Definition at line 726 of file Rational.h.
MpiThrow()
void Util::MpiThrow (Exception & e)
Function to throw exception in MPI code.
If MPI is not initialized, this function writes the message and calls MPI Abort. If MPI is not initialized, it simply throws the Exception.
Parameters
e Exception to be thrown.
Definition at line 90 of file Exception.cpp.
References Util::Log::close(), Util::Log::file(), and Util::Exception::message().
initStatic()
void Util::initStatic ()
Guarantee initialization of all static class members in Util namespace.
Definition at line 26 of file initStatic.cpp.
References Util::Format::initStatic(), Util::Constants::initStatic(), Util::Log::initStatic(), Util::Memory::initStatic(), Util::ParamComponent::initStatic(), Util::Tensor::initStatic(), Util::Vector::initStatic(), and Util::IntVector::initStatic().
checkRequiredIstream()
void Util::checkRequiredIstream (std::istream & in)
Check status of a std::istream just before reading required variable.
Throw Exception with appropriate error message if not good.
Parameters
in input stream from which to read.
Definition at line 124 of file ioUtil.cpp.
References UTIL_THROW.
baseOffset()
template<typename D , typename B >
ptrdiff_t Util::baseOffset (D & object)
Template for calculating offsets of base class subobjects.
Types: D - derived class B - base class
Definition at line 40 of file Offset.h.
send< bool >()
template<>
void Util::send< bool > (MPI::Comm & comm, bool & data, int dest, int tag)
Explicit specialization of send for bool data.
Definition at line 19 of file MpiSendRecv.cpp.
recv< bool >()
template<>
void Util::recv< bool > (MPI::Comm & comm, bool & data, int source, int tag)
Explicit specialization of recv for bool data.
Definition at line 26 of file MpiSendRecv.cpp.
bcast< bool >()
template<>
void Util::bcast< bool > (MPI::Intracomm & comm, bool & data, int root)
Explicit specialization of bcast for bool data.
Definition at line 34 of file MpiSendRecv.cpp.
Referenced by Util::Parameter::load(), Util::ParamComposite::loadOptional(), Util::Begin::readParam(), and Util::Parameter::readParam().
send< std::string >()
template<>
void Util::send< std::string > (MPI::Comm & comm, std::string & data, int dest, int tag)
Explicit specialization of send for std::string data.
Definition at line 48 of file MpiSendRecv.cpp.
recv< std::string >()
template<>
void Util::recv< std::string > (MPI::Comm & comm, std::string & data, int source, int tag)
Explicit specialization of recv for std::string data.
Definition at line 64 of file MpiSendRecv.cpp.
bcast< std::string >()
template<>
void Util::bcast< std::string > (MPI::Intracomm & comm, std::string & data, int root)
Explicit specialization of bcast for std::string data.
Definition at line 80 of file MpiSendRecv.cpp.
send() [1/4]
template<typename T >
void Util::send (MPI::Comm & comm, T & data, int dest, int tag)
Send a single T value.
Throws an Exception if no associated MPI data type is available, i.e., if MpiTraits<T>::hasType is false.
Parameters
comm MPI communicator
data value
dest MPI rank of receiving processor in comm
tag user-defined integer identifier for message
Definition at line 97 of file MpiSendRecv.h.
References UTIL_THROW.
recv() [1/4]
template<typename T >
void Util::recv (MPI::Comm & comm, T & data, int source, int tag)
Receive a single T value.
Throws an Exception if no associated MPI data type is available, i.e., if MpiTraits<T>::hasType is false.
Parameters
comm MPI communicator
data value
source MPI rank of sending processor in comm
tag user-defined integer identifier for message
Definition at line 116 of file MpiSendRecv.h.
References UTIL_THROW.
bcast() [1/4]
template<typename T >
void Util::bcast (MPI::Intracomm & comm, T & data, int root)
Broadcast a single T value.
Throws an Exception if no associated MPI data type is available, i.e., if MpiTraits<T>::hasType is false.
Parameters
comm MPI communicator
data value
root MPI rank of root (sending) processor in comm
Definition at line 134 of file MpiSendRecv.h.
References UTIL_THROW.
send() [2/4]
template<typename T >
void Util::send (MPI::Comm & comm, T * array, int count, int dest, int tag)
Send a C-array of T values.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar send<T>.
Parameters
comm MPI communicator
array address of first element in array
count number of elements in array
dest MPI rank of destination (receiving) processor in comm
tag user-defined integer identifier for this message
Definition at line 156 of file MpiSendRecv.h.
recv() [2/4]
template<typename T >
void Util::recv (MPI::Comm & comm, T * array, int count, int source, int tag)
Receive a C-array of T objects.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar recv<T>.
Parameters
comm MPI communicator
array address of first element in array
count number of elements in array
source MPI rank of source (sending) processor in comm
tag user-defined integer identifier for this message
Definition at line 182 of file MpiSendRecv.h.
bcast() [2/4]
template<typename T >
void Util::bcast (MPI::Intracomm & comm, T * array, int count, int root)
Broadcast a C-array of T objects.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar bcast<T>.
Parameters
comm MPI communicator
array address of first element in array
count number of elements in array
root MPI rank of root (sending) processor in comm
Definition at line 207 of file MpiSendRecv.h.
send() [3/4]
template<typename T >
void Util::send (MPI::Comm & comm, DArray< T > & array, int count, int dest, int tag)
Send a DArray<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar send<T> method.
Parameters
comm MPI communicator
array DArray object
count logical number of elements in array
dest MPI rank of destination (receiving) processor in comm
tag user-defined integer identifier for this message
Definition at line 235 of file MpiSendRecv.h.
References Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), and UTIL_THROW.
recv() [3/4]
template<typename T >
void Util::recv (MPI::Comm & comm, DArray< T > & array, int count, int source, int tag)
Receive a DArray<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar recv<T> method.
Parameters
comm MPI communicator
array DArray object
count logical number of elements in array
source MPI rank of source (sending) processor in comm
tag user-defined integer identifier for this message
Definition at line 269 of file MpiSendRecv.h.
References Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), and UTIL_THROW.
bcast() [3/4]
template<typename T >
void Util::bcast (MPI::Intracomm & comm, DArray< T > & array, int count, int root)
Broadcast a DArray<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar bcast<T>.
Parameters
comm MPI communicator
array address of first element in array
count number of elements in array
root MPI rank of root (sending) processor in comm
Definition at line 302 of file MpiSendRecv.h.
References Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), and UTIL_THROW.
send() [4/4]
template<typename T >
void Util::send (MPI::Comm & comm, DMatrix< T > & matrix, int m, int n, int dest, int tag)
Send a DMatrix<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar send<T>.
Parameters
comm MPI communicator
matrix DMatrix object to send
m logical number of rows in matrix
n logical number of columns in matrix
dest MPI rank of destination (receiving) processor in comm
tag user-defined integer identifier for this message
Definition at line 339 of file MpiSendRecv.h.
References Util::Matrix< Data >::capacity1(), Util::Matrix< Data >::capacity2(), Util::DMatrix< Data >::isAllocated(), and UTIL_THROW.
recv() [4/4]
template<typename T >
void Util::recv (MPI::Comm & comm, DMatrix< T > & matrix, int m, int n, int source, int tag)
Receive a DMatrix<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar recv<T>.
Parameters
comm MPI communicator
matrix DMatrix object to receive
m logical number of rows in matrix
n logical number of columns in matrix
source MPI rank of source (sending) processor in comm
tag user-defined integer identifier for this message
Definition at line 383 of file MpiSendRecv.h.
References Util::Matrix< Data >::capacity1(), Util::Matrix< Data >::capacity2(), Util::DMatrix< Data >::isAllocated(), and UTIL_THROW.
bcast() [4/4]
template<typename T >
void Util::bcast (MPI::Intracomm & comm, DMatrix< T > & matrix, int m, int n, int root)
Broadcast a DMatrix<T> container.
Throws an exception if their exists neither an associated MPI data type nor an explicit specialization of the scalar bcast<T>.
Parameters
comm MPI communicator
matrix DMatrix object
m logical number of rows in matrix
n logical number of columns in matrix
root MPI rank of root (sending) processor in comm
Definition at line 427 of file MpiSendRecv.h.
References Util::Matrix< Data >::capacity1(), Util::Matrix< Data >::capacity2(), Util::DMatrix< Data >::isAllocated(), and UTIL_THROW.
operator>>() [7/10]
std::istream & Util::operator>> (std::istream & in, Label label)
Extractor for Label.
Parameters
in input stream
label Label to be read from file
Definition at line 104 of file Label.cpp.
References Util::Log::file(), Util::Label::isRequired(), UTIL_CHECK, and UTIL_THROW.
operator<<() [8/11]
std::ostream & Util::operator<< (std::ostream & out, Label label)
Inserter for Label.
Parameters
out output stream
label Label to be written to file
Definition at line 158 of file Label.cpp.
References Util::Label::LabelWidth.
isNull() [1/3]
template<typename T >
bool Util::isNull (FlexPtr< T > p) [inline]
Return true iff the enclosed built-in pointer is null.
Definition at line 143 of file FlexPtr.h.
References Util::FlexPtr< T >::get().
isNull() [2/3]
template<typename T >
bool Util::isNull (T * ptr) [inline]
Return true iff a built-in pointer is null.
Definition at line 18 of file isNull.h.
isNull() [3/3]
template<typename T >
bool Util::isNull (ScopedPtr< T > p) [inline]
Return true iff the enclosed built-in pointer is null.
Definition at line 90 of file ScopedPtr.h.
References Util::ScopedPtr< T >::get().
operator==() [5/13]
bool Util::operator== (const IntVector & v1, const IntVector & v2)
Equality for IntVectors.
Definition at line 24 of file IntVector.cpp.
References Dimension.
operator==() [6/13]
bool Util::operator== (const IntVector & v1, const int * v2)
Equality of IntVector and C array.
Definition at line 35 of file IntVector.cpp.
References Dimension.
operator==() [7/13]
bool Util::operator== (const int * v1, const IntVector & v2)
Equality of C array and IntVector.
Definition at line 45 of file IntVector.cpp.
operator!=() [5/13]
bool Util::operator!= (const IntVector & v1, const IntVector & v2)
Inequality of two IntVectors.
Definition at line 50 of file IntVector.cpp.
operator!=() [6/13]
bool Util::operator!= (const IntVector & v1, const int * v2)
Inequality of IntVector and C array.
Definition at line 54 of file IntVector.cpp.
operator!=() [7/13]
bool Util::operator!= (const int * v1, const IntVector & v2)
Inequality of C array and IntVector.
Definition at line 58 of file IntVector.cpp.
operator>>() [8/10]
std::istream & Util::operator>> (std::istream & in, IntVector & vector)
istream extractor for a IntVector.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector IntVector to be read from stream
Returns
modified input stream
Definition at line 64 of file IntVector.cpp.
References Dimension.
operator<<() [9/11]
std::ostream & Util::operator<< (std::ostream & out, const IntVector & vector)
ostream inserter for a IntVector.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector IntVector to be written to stream
Returns
modified output stream
Definition at line 75 of file IntVector.cpp.
References Dimension.
operator==() [8/13]
bool Util::operator== (const Tensor & t1, const Tensor & t2)
Equality for Tensors.
Definition at line 43 of file Tensor.cpp.
References DimensionSq.
operator==() [9/13]
bool Util::operator== (const Tensor & t1, const double a2[][Dimension])
Equality of Tensor and 2D C array.
Definition at line 56 of file Tensor.cpp.
References Dimension.
operator==() [10/13]
bool Util::operator== (const double a1[][Dimension], const Tensor & t2)
Equality of C array and Tensor.
Definition at line 71 of file Tensor.cpp.
operator!=() [8/13]
bool Util::operator!= (const Tensor & t1, const Tensor & t2)
Negation of t1 == t2 (tensors t1 and t2)
Inequality of two Tensors.
Definition at line 79 of file Tensor.cpp.
operator!=() [9/13]
bool Util::operator!= (const Tensor & t1, const double a2[][Dimension])
Negation of t1 == a2 (tensor t1, 2D array a2)
Inequality of Tensor and C array.
Definition at line 83 of file Tensor.cpp.
operator!=() [10/13]
bool Util::operator!= (const double a1[][Dimension], const Tensor & t2)
Negation of t1 == a2 (tensor t2, 2D array a1)
Inequality of C array and Tensor.
Definition at line 87 of file Tensor.cpp.
operator>>() [9/10]
std::istream & Util::operator>> (std::istream & in, Tensor & tensor)
istream extractor for a Tensor.
Input elements of a tensor from stream, without line breaks.
Parameters
in input stream
tensor Tensor to be read from stream
Returns
modified input stream
Definition at line 93 of file Tensor.cpp.
References DimensionSq.
operator<<() [10/11]
std::ostream & Util::operator<< (std::ostream & out, const Tensor & tensor)
ostream inserter for a Tensor.
Output elements of a tensor to stream, without line breaks.
Parameters
out output stream
tensor Tensor to be written to stream
Returns
modified output stream
Definition at line 104 of file Tensor.cpp.
References DimensionSq.
operator==() [11/13]
bool Util::operator== (const Vector & v1, const Vector & v2)
Equality for Vectors.
Definition at line 26 of file Vector.cpp.
References Dimension.
operator==() [12/13]
bool Util::operator== (const Vector & v1, const double * v2)
Equality of Vector and C array.
Definition at line 36 of file Vector.cpp.
References Dimension.
operator==() [13/13]
bool Util::operator== (const double * v1, const Vector & v2)
Equality of C array and Vector.
Definition at line 48 of file Vector.cpp.
operator!=() [11/13]
bool Util::operator!= (const Vector & v1, const Vector & v2)
Inequality of two Vectors.
Definition at line 53 of file Vector.cpp.
operator!=() [12/13]
bool Util::operator!= (const Vector & v1, const double * v2)
Inequality of Vector and C array.
Definition at line 56 of file Vector.cpp.
operator!=() [13/13]
bool Util::operator!= (const double * v1, const Vector & v2)
Inequality of C array and Vector.
Definition at line 59 of file Vector.cpp.
operator>>() [10/10]
std::istream & Util::operator>> (std::istream & in, Vector & vector)
istream extractor for a Vector.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector Vector to be read from stream
Returns
modified input stream
Definition at line 65 of file Vector.cpp.
References Dimension.
operator<<() [11/11]
std::ostream & Util::operator<< (std::ostream & out, const Vector & vector)
ostream inserter for a Vector.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector Vector to be written to stream
Returns
modified output stream
Definition at line 76 of file Vector.cpp.
References Dimension.