Util::SymmTensorAverage Class Reference
Calculates averages of all components of a Tensor-valued variable.
#include <SymmTensorAverage.h>
Public Member Functions
SymmTensorAverage (int blockFactor=2)
Constructor.
virtual ~SymmTensorAverage ()
Destructor.
void setNSamplePerBlock (int nSamplePerBlock)
Set nSamplePerBlock.
void readParameters (std::istream &in)
Read parameter nSamplePerBlock from file and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this to or from an archive.
void clear ()
Clear all accumulators, set to empty initial state.
void sample (const Tensor &value)
Add a sampled value to the ensemble.
const Average & operator() (int i, int j)
Access the Average object for one tensor component.
int nSamplePerBlock () const
Get number of samples per block average.
int iBlock () const
Get number of samples in current block average.
bool isBlockComplete () const
Is the current block average complete?
Additional Inherited Members
Detailed Description
Calculates averages of all components of a Tensor-valued variable.
SymmTensorAverage is a simple container for an array of Average objects, each of which calculates averages and error estimates for one component of a Tensor.
Definition at line 31 of file SymmTensorAverage.h.
Constructor & Destructor Documentation
SymmTensorAverage()
Util::SymmTensorAverage::SymmTensorAverage (int blockFactor = 2)
Constructor.
Parameters
blockFactor ratio of block sizes for subsequent stages.
Definition at line 19 of file SymmTensorAverage.cpp.
References Util::Dimension, and Util::ParamComposite::setClassName().
 SymmTensorAverage()
Util::SymmTensorAverage::~SymmTensorAverage () [virtual]
Destructor.
Definition at line 38 of file SymmTensorAverage.cpp.
Member Function Documentation
setNSamplePerBlock()
void Util::SymmTensorAverage::setNSamplePerBlock (int nSamplePerBlock)
Set nSamplePerBlock.
If nSamplePerBlock > 0, the sample function will increment block averages, and reset the average every nSamplePerBlock samples.
If nSamplePerBlock == 0, block averaging is disabled. This is the default (i.e., the initial value set in the constructor).
Parameters
nSamplePerBlock number of samples per block average output
Definition at line 44 of file SymmTensorAverage.cpp.
References Util::Dimension, nSamplePerBlock(), and UTIL_THROW.
readParameters()
void Util::SymmTensorAverage::readParameters (std::istream & in) [virtual]
Read parameter nSamplePerBlock from file and initialize.
See setNSamplePerBlock() for discussion of value.
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Definition at line 63 of file SymmTensorAverage.cpp.
References Util::Dimension, and UTIL_THROW.
loadParameters()
void Util::SymmTensorAverage::loadParameters (Serializable::IArchive & ar) [virtual]
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::ParamComposite.
Definition at line 82 of file SymmTensorAverage.cpp.
References Util::Dimension, and UTIL_THROW.
save()
void Util::SymmTensorAverage::save (Serializable::OArchive & ar) [virtual]
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::ParamComposite.
Definition at line 102 of file SymmTensorAverage.cpp.
serialize()
template<class Archive >
void Util::SymmTensorAverage::serialize (Archive & ar, const unsigned int version)
Serialize this to or from an archive.
Parameters
ar input or output archive
version file version id
Definition at line 181 of file SymmTensorAverage.h.
References Util::Dimension.
clear()
void Util::SymmTensorAverage::clear ()
Clear all accumulators, set to empty initial state.
Definition at line 108 of file SymmTensorAverage.cpp.
References Util::Dimension.
sample()
void Util::SymmTensorAverage::sample (const Tensor & value)
Add a sampled value to the ensemble.
Parameters
value sampled value
Definition at line 124 of file SymmTensorAverage.cpp.
References Util::Dimension.
operator()()
const Average & Util::SymmTensorAverage::operator() (int i, int j)
Access the Average object for one tensor component.
Parameters
i first index of associated tensor component
j second index of associated tensor component
Returns
Average object associated with element (i, j)
Definition at line 145 of file SymmTensorAverage.cpp.
nSamplePerBlock()
int Util::SymmTensorAverage::nSamplePerBlock () const [inline]
Get number of samples per block average.
Returns zero if block averaging is disabled.
Returns
number of samples per block (or 0 if disabled).
Definition at line 162 of file SymmTensorAverage.h.
Referenced by setNSamplePerBlock().
iBlock()
int Util::SymmTensorAverage::iBlock () const [inline]
Get number of samples in current block average.
Returns 0 if block averaging is disabled (i.e., nSamplePerBlock == 0).
Returns
number of samples in current block (or 0 if disabled).
Definition at line 168 of file SymmTensorAverage.h.
isBlockComplete()
bool Util::SymmTensorAverage::isBlockComplete () const [inline]
Is the current block average complete?
Returns
(iBlock > 0) && (iBlock == nSamplePerBlock)
Definition at line 174 of file SymmTensorAverage.h.
The documentation for this class was generated from the following files:
SymmTensorAverage.h
SymmTensorAverage.cpp