Pscf::Homogeneous::Mixture Class Reference
A spatially homogeneous mixture.
#include <Mixture.h>
Public Member Functions
Mixture ()
Constructor.
~Mixture ()
Destructor.
 Initialization.
virtual void readParameters (std::istream &in)
Read parameters from file and initialize.
void setNMolecule (int nMonomer)
Set the number of molecular species and allocate memory.
void setNMonomer (int nMonomer)
Set the number of monomer types.
 Thermodynamics Computations
void setComposition (DArray< double > const &phi)
Set system composition.
void computeMu (Interaction const &interaction, double xi=0.0)
Compute chemical potential from preset composition.
void computePhi (Interaction const &interaction, DArray< double > const &mu, DArray< double > const &phi, double &xi)
Compute composition from chemical potentials.
void computeFreeEnergy (Interaction const &interaction)
Compute Helmholtz free energy and pressure.
Accessors
Molecule & molecule (int id)
Get a molecule object.
double mu (int id) const
Return chemical potential for one species.
double phi (int id) const
Return molecular volume fraction for one species.
double c (int id) const
Return monomer volume fraction for one monomer type.
double fHelmholtz () const
Return Helmholtz free energy per monomer / kT.
double pressure () const
Return pressure in units of kT / monomer volume.
int nMolecule () const
Get number of molecule species.
int nMonomer () const
Get number of monomer types.
void validate () const
Validate all data structures.
Additional Inherited Members
Detailed Description
A spatially homogeneous mixture.
Definition at line 33 of file pscf/homogeneous/Mixture.h.
Constructor & Destructor Documentation
Mixture()
Pscf::Homogeneous::Mixture::Mixture ()
Constructor.
Definition at line 21 of file Mixture.cpp.
References Util::ParamComposite::setClassName().
 Mixture()
Pscf::Homogeneous::Mixture::~Mixture ()
Destructor.
Definition at line 45 of file Mixture.cpp.
Member Function Documentation
readParameters()
void Pscf::Homogeneous::Mixture::readParameters (std::istream & in) [virtual]
Read parameters from file and initialize.
Parameters
in input parameter file
Reimplemented from Util::ParamComposite.
Definition at line 51 of file Mixture.cpp.
References Util::DArray< Data >::allocate(), Util::ParamComposite::readParamComposite(), UTIL_ASSERT, and validate().
setNMolecule()
void Pscf::Homogeneous::Mixture::setNMolecule (int nMonomer)
Set the number of molecular species and allocate memory.
Definition at line 71 of file Mixture.cpp.
References Util::DArray< Data >::allocate(), nMolecule(), and UTIL_ASSERT.
setNMonomer()
void Pscf::Homogeneous::Mixture::setNMonomer (int nMonomer)
Set the number of monomer types.
Definition at line 80 of file Mixture.cpp.
References Util::DArray< Data >::allocate(), nMonomer(), and UTIL_ASSERT.
setComposition()
void Pscf::Homogeneous::Mixture::setComposition (DArray< double > const & phi)
Set system composition.
Parameters
phi array of molecular volume fractions.
Definition at line 91 of file Mixture.cpp.
References phi(), UTIL_ASSERT, UTIL_CHECK, and validate().
Referenced by computePhi().
computeMu()
void Pscf::Homogeneous::Mixture::computeMu (Interaction const & interaction, double xi = 0.0)
Compute chemical potential from preset composition.
Precondition: setComposition must be called prior. Postcondition: Upon return, mu array is set.
Parameters
interaction excess free energy model (input)
xi Lagrange multiplier field (input)
Definition at line 149 of file Mixture.cpp.
References c(), Pscf::Homogeneous::Molecule::clump(), Pscf::Interaction::computeW(), Pscf::Homogeneous::Clump::monomerId(), mu(), Pscf::Homogeneous::Molecule::nClump(), Pscf::Interaction::nMonomer(), Pscf::Homogeneous::Clump::size(), Pscf::Homogeneous::Molecule::size(), and UTIL_CHECK.
Referenced by computePhi().
computePhi()
void Pscf::Homogeneous::Mixture::computePhi (Interaction const & interaction, DArray< double > const & mu, DArray< double > const & phi, double & xi)
Compute composition from chemical potentials.
Parameters
interaction excess free energy model (input)
mu target molecular chemical potentials (input)
phi guess of molecular volume fractions (input)
xi Lagrange multiplier field (input/output)
Definition at line 180 of file Mixture.cpp.
References Pscf::LuSolver::allocate(), Util::DMatrix< Data >::allocate(), Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), Pscf::Homogeneous::Molecule::clump(), Pscf::Interaction::computeDwDc(), Pscf::LuSolver::computeLU(), computeMu(), molecule(), Pscf::Homogeneous::Clump::monomerId(), mu(), Pscf::Homogeneous::Molecule::nClump(), Pscf::Interaction::nMonomer(), phi(), setComposition(), Pscf::Homogeneous::Clump::size(), Pscf::Homogeneous::Molecule::size(), Pscf::LuSolver::solve(), UTIL_ASSERT, and UTIL_THROW.
computeFreeEnergy()
void Pscf::Homogeneous::Mixture::computeFreeEnergy (Interaction const & interaction)
Compute Helmholtz free energy and pressure.
Preconditions and postconditions:
Precondition
setComposition must be called prior.
computeMu must be called prior.
Postcondition
fHelmholtz and pressure are set.
Parameters
interaction excess free energy model (input)
Definition at line 374 of file Mixture.cpp.
References Pscf::Interaction::fHelmholtz().
molecule()
Molecule & Pscf::Homogeneous::Mixture::molecule (int id) [inline]
Get a molecule object.
Parameters
id integer molecule species index (0 <= id < nMolecule)
Definition at line 285 of file pscf/homogeneous/Mixture.h.
References UTIL_ASSERT.
Referenced by computePhi().
mu()
double Pscf::Homogeneous::Mixture::mu (int id) const [inline]
Return chemical potential for one species.
Parameters
id integer molecule species index (0 <= id < nMolecule)
Definition at line 292 of file pscf/homogeneous/Mixture.h.
References UTIL_ASSERT.
Referenced by computeMu(), and computePhi().
phi()
double Pscf::Homogeneous::Mixture::phi (int id) const [inline]
Return molecular volume fraction for one species.
Parameters
id integer molecule species index (0 <= id < nMolecule)
Definition at line 299 of file pscf/homogeneous/Mixture.h.
References UTIL_ASSERT.
Referenced by computePhi(), and setComposition().
c()
double Pscf::Homogeneous::Mixture::c (int id) const [inline]
Return monomer volume fraction for one monomer type.
Parameters
id monomer type index (0 <= id < nMonomer)
Definition at line 306 of file pscf/homogeneous/Mixture.h.
References UTIL_ASSERT.
Referenced by computeMu().
fHelmholtz()
double Pscf::Homogeneous::Mixture::fHelmholtz () const [inline]
Return Helmholtz free energy per monomer / kT.
Definition at line 313 of file pscf/homogeneous/Mixture.h.
pressure()
double Pscf::Homogeneous::Mixture::pressure () const [inline]
Return pressure in units of kT / monomer volume.
Definition at line 316 of file pscf/homogeneous/Mixture.h.
nMolecule()
int Pscf::Homogeneous::Mixture::nMolecule () const [inline]
Get number of molecule species.
Definition at line 319 of file pscf/homogeneous/Mixture.h.
Referenced by setNMolecule().
nMonomer()
int Pscf::Homogeneous::Mixture::nMonomer () const [inline]
Get number of monomer types.
Definition at line 322 of file pscf/homogeneous/Mixture.h.
Referenced by setNMonomer().
validate()
void Pscf::Homogeneous::Mixture::validate () const
Validate all data structures.
Throw an exception if an error is found.
Definition at line 400 of file Mixture.cpp.
References Pscf::Homogeneous::Molecule::clump(), Pscf::Homogeneous::Clump::monomerId(), Pscf::Homogeneous::Molecule::nClump(), and UTIL_ASSERT.
Referenced by readParameters(), and setComposition().
The documentation for this class was generated from the following files:
pscf/homogeneous/Mixture.h
Mixture.cpp