Pscf::Field< T > Class Template Reference
Base class template for a field defined on a spatial grid.
#include <Field.h>
Public Member Functions
Field ()
Constructor.
Field (Field< T > const &other)
Copy constructor.
Field< T > & operator= (Field< T > const &other)
Assignment operator.
Field< T > & operator= (T &scalar)
Assignment - assign all elements to a common scalar.
Field< T > & operator+= (Field< T > &other)
Increment operator - add one field by another.
Field< T > & operator-= (Field< T > &other)
Decrement operator - subtract one field from another.
Field< T > & operator*= (T scalar)
Multiplication operator - multiply one field by a scalar.
Field< T > & operator*= (Field< T > &other)
Pointwise multipication of one field by another.
void setToZero ()
Set all elements to zero.
T average () const
Compute and return average of all elements.
Additional Inherited Members
Detailed Description
template<typename T = double>
class Pscf::Field< T >
Base class template for a field defined on a spatial grid.
Derived from DArray<T>, and provides useful arithmetic operations.
Definition at line 23 of file Field.h.
Constructor & Destructor Documentation
Field() [1/2]
template<typename T = double>
Pscf::Field< T >::Field ()
Constructor.
Field() [2/2]
template<class T >
Pscf::Field< T >::Field (Field< T > const & other)
Copy constructor.
Definition at line 98 of file Field.h.
References Util::Memory::allocate(), Util::Array< double >::capacity_, Util::Array< double >::data_, Util::DArray< double >::isAllocated(), and UTIL_THROW.
Member Function Documentation
operator=() [1/2]
template<class T >
Field< T > & Pscf::Field< T >::operator= (Field< T > const & other)
Assignment operator.
Definition at line 122 of file Field.h.
References Util::Array< double >::capacity(), Util::Array< double >::capacity_, Util::DArray< double >::isAllocated(), and UTIL_THROW.
operator=() [2/2]
template<typename T >
Field< T > & Pscf::Field< T >::operator= (T & scalar)
Assignment - assign all elements to a common scalar.
Definition at line 150 of file Field.h.
References UTIL_THROW.
operator+=()
template<typename T >
Field< T > & Pscf::Field< T >::operator+= (Field< T > & other)
Increment operator - add one field by another.
Definition at line 165 of file Field.h.
References Util::Array< double >::capacity_, Util::Array< double >::data_, Util::DArray< double >::isAllocated(), and UTIL_THROW.
operator-=()
template<typename T >
Field< T > & Pscf::Field< T >::operator-= (Field< T > & other)
Decrement operator - subtract one field from another.
Definition at line 186 of file Field.h.
References Util::Array< double >::capacity_, Util::Array< double >::data_, Util::DArray< double >::isAllocated(), and UTIL_THROW.
operator*=() [1/2]
template<typename T >
Field< T > & Pscf::Field< T >::operator*= (T scalar)
Multiplication operator - multiply one field by a scalar.
Definition at line 210 of file Field.h.
References UTIL_THROW.
operator*=() [2/2]
template<typename T >
Field< T > & Pscf::Field< T >::operator*= (Field< T > & other)
Pointwise multipication of one field by another.
Definition at line 227 of file Field.h.
References Util::Array< double >::capacity_, Util::Array< double >::data_, Util::DArray< double >::isAllocated(), and UTIL_THROW.
setToZero()
template<typename T >
void Pscf::Field< T >::setToZero
Set all elements to zero.
Definition at line 250 of file Field.h.
average()
template<typename T >
T Pscf::Field< T >::average
Compute and return average of all elements.
Definition at line 261 of file Field.h.
The documentation for this class was generated from the following file:
Field.h